<?php
$table_schema[] = "INSERT INTO `" . PREFIX . "_job_specialties` VALUES (1, 1, 'По любой специальности', 'po-lyuboj-specialnosti'),
(2, 1, 'Администратор', 'administrator'),
(3, 1, 'Аналитик', 'analitik'),
(4, 1, 'Аудитор', 'auditor'),
(5, 1, 'Банковский служащий', 'bankovskij-sluzhashhij'),
(6, 1, 'Бренд-менеджер', 'brend-menedzher'),
(7, 1, 'Брокер / Трейдер', 'broker-trejder'),
(8, 1, 'Бухгалтер', 'buxgalter'),
(9, 1, 'Веб-мастер', 'veb-master'),
(10, 1, 'Водитель', 'voditel'),
(11, 1, 'Водитель-международник', 'voditel-mezhdunarodnik'),
(12, 1, 'Главный бухгалтер', 'glavnyj-buxgalter'),
(13, 1, 'Дизайнер', 'dizajner'),
(14, 1, 'Директор', 'direktor'),
(15, 1, 'Директор по информационным технологиям', 'direktor-po-informacionnym-texnologiyam'),
(16, 1, 'Директор по маркетингу и рекламе', 'direktor-po-marketingu-i-reklame'),
(17, 1, 'Директор по персоналу', 'direktor-po-personalu'),
(18, 1, 'Зам.директора', 'zam.direktora'),
(19, 1, 'Инспектор по кадрам', 'inspektor-po-kadram'),
(20, 1, 'Кассир', 'kassir'),
(21, 1, 'Коммерческий директор', 'kommercheskij-direktor'),
(22, 1, 'Консультант', 'konsultant'),
(23, 1, 'Курьер', 'kurer'),
(24, 1, 'Маклер', 'makler'),
(25, 1, 'Менеджер (-консультант)', 'menedzher-konsultant'),
(26, 1, 'Менеджер по PR', 'menedzher-po-pr'),
(27, 1, 'Менеджер по ВЭД', 'menedzher-po-vyed'),
(28, 1, 'Менеджер по закупкам', 'menedzher-po-zakupkam'),
(29, 1, 'Менеджер по информационным технологиям', 'menedzher-po-informacionnym-texnologiyam'),
(30, 1, 'Менеджер по логистике', 'menedzher-po-logistike'),
(31, 1, 'Менеджер по маркетингу и рекламе', 'menedzher-po-marketingu-i-reklame'),
(32, 1, 'Менеджер по персоналу', 'menedzher-po-personalu'),
(33, 1, 'Менеджер по продажам', 'menedzher-po-prodazham'),
(34, 1, 'Менеджер по работе с клиентами', 'menedzher-po-rabote-s-klientami'),
(35, 1, 'Менеджер проекта', 'menedzher-proekta'),
(36, 1, 'Мерчандайзер', 'merchandajzer'),
(37, 1, 'Начальник отдела', 'nachalnik-otdela'),
(38, 1, 'Оператор ПК', 'operator-pk'),
(39, 1, 'Офис-менеджер', 'ofis-menedzher'),
(40, 1, 'Охранник', 'oxrannik'),
(41, 1, 'Оценщик', 'ocenshhik'),
(42, 1, 'Переводчик', 'perevodchik'),
(43, 1, 'Преподаватель', 'prepodavatel'),
(44, 1, 'Пресс-секретарь', 'press-sekretar'),
(45, 1, 'Программист', 'programmist'),
(46, 1, 'Региональный представитель', 'regionalnyj-predstavitel'),
(47, 1, 'Референт', 'referent'),
(48, 1, 'Риэлтор', 'riyeltor'),
(49, 1, 'Секретарь', 'sekretar'),
(50, 1, 'Секретарь-референт', 'sekretar-referent'),
(51, 1, 'Специалист по бизнес-процессам', 'specialist-po-biznes-processam'),
(52, 1, 'Специалист по закупкам', 'specialist-po-zakupkam'),
(53, 1, 'Специалист по рекламе', 'specialist-po-reklame'),
(54, 1, 'Специалист по ремонту ПК и оргтехники', 'specialist-po-remontu-pk-i-orgtexniki'),
(55, 1, 'Специалист по сертификации', 'specialist-po-sertifikacii'),
(56, 1, 'Супервайзер', 'supervajzer'),
(57, 1, 'Таможенный декларант / агент', 'tamozhennyj-deklarant-agent'),
(58, 1, 'Технический аналитик', 'texnicheskij-analitik'),
(59, 1, 'Торговый агент / Агент', 'torgovyj-agent-agent'),
(60, 1, 'Управляющий', 'upravlyayushhij'),
(61, 1, 'Финансовый директор', 'finansovyj-direktor'),
(62, 1, 'Экономист (-менеджер)', 'yekonomist-menedzher'),
(63, 1, 'Экспедитор / Логист', 'yekspeditor-logist'),
(64, 1, 'Электрик', 'yelektrik'),
(65, 1, 'Юрист', 'yurist'),
(66, 2, 'По любой специальности', 'po-lyuboj-specialnosti'),
(67, 2, 'Администратор', 'administrator'),
(68, 2, 'Бухгалтер', 'buxgalter'),
(69, 2, 'Водитель', 'voditel'),
(70, 2, 'Воспитатель', 'vospitatel'),
(71, 2, 'Главный бухгалтер', 'glavnyj-buxgalter'),
(72, 2, 'Грузчик', 'gruzchik'),
(73, 2, 'Гувернер', 'guverner'),
(74, 2, 'Директор', 'direktor'),
(75, 2, 'Директор по информационным технологиям', 'direktor-po-informacionnym-texnologiyam'),
(76, 2, 'Директор по маркетингу и рекламе', 'direktor-po-marketingu-i-reklame'),
(77, 2, 'Директор по персоналу', 'direktor-po-personalu'),
(78, 2, 'Диспетчер', 'dispetcher'),
(79, 2, 'Домработница', 'domrabotnica'),
(80, 2, 'Заведующий', 'zaveduyushhij'),
(81, 2, 'Закройщик', 'zakrojshhik'),
(82, 2, 'Зам.директора', 'zam.direktora'),
(83, 2, 'Инженер', 'inzhener'),
(84, 2, 'Инспектор по кадрам', 'inspektor-po-kadram'),
(85, 2, 'Кассир', 'kassir'),
(86, 2, 'Коммерческий директор', 'kommercheskij-direktor'),
(87, 2, 'Консультант', 'konsultant'),
(88, 2, 'Курьер', 'kurer'),
(89, 2, 'Маляр', 'malyar'),
(90, 2, 'Мастер', 'master'),
(91, 2, 'Мастер по маникюру / педикюру', 'master-po-manikyuru-pedikyuru'),
(92, 2, 'Менеджер (-консультант)', 'menedzher-konsultant'),
(93, 2, 'Менеджер по PR', 'menedzher-po-pr'),
(94, 2, 'Менеджер по информационным технологиям', 'menedzher-po-informacionnym-texnologiyam'),
(95, 2, 'Менеджер по маркетингу и рекламе', 'menedzher-po-marketingu-i-reklame'),
(96, 2, 'Менеджер по продажам', 'menedzher-po-prodazham'),
(97, 2, 'Менеджер по работе с клиентами', 'menedzher-po-rabote-s-klientami'),
(98, 2, 'Начальник отдела', 'nachalnik-otdela'),
(99, 2, 'Няня', 'nyanya'),
(100, 2, 'Оператор', 'operator'),
(101, 2, 'Оператор ПК', 'operator-pk'),
(102, 2, 'Офис-менеджер', 'ofis-menedzher'),
(103, 2, 'Парикмахер', 'parikmaxer'),
(104, 2, 'Переводчик', 'perevodchik'),
(105, 2, 'Плиточник', 'plitochnik'),
(106, 2, 'Повар', 'povar'),
(107, 2, 'Портной', 'portnoj'),
(108, 2, 'Пресс-секретарь', 'press-sekretar'),
(109, 2, 'Разнорабочий', 'raznorabochij'),
(110, 2, 'Региональный представитель', 'regionalnyj-predstavitel'),
(111, 2, 'Референт', 'referent'),
(112, 2, 'Сантехник', 'santexnik'),
(113, 2, 'Секретарь', 'sekretar'),
(114, 2, 'Секретарь-референт', 'sekretar-referent'),
(115, 2, 'Сиделка', 'sidelka'),
(116, 2, 'Слесарь (-ремонтник)', 'slesar-remontnik'),
(117, 2, 'Специалист по охране труда', 'specialist-po-oxrane-truda'),
(118, 2, 'Специалист по рекламе', 'specialist-po-reklame'),
(119, 2, 'Специалист по ремонту ПК и оргтехники', 'specialist-po-remontu-pk-i-orgtexniki'),
(120, 2, 'Столяр', 'stolyar'),
(121, 2, 'Супервайзер', 'supervajzer'),
(122, 2, 'Торговый агент / Агент', 'torgovyj-agent-agent'),
(123, 2, 'Уборщица', 'uborshhica'),
(124, 2, 'Финансовый директор', 'finansovyj-direktor'),
(125, 2, 'Фотограф', 'fotograf'),
(126, 2, 'Швея', 'shveya'),
(127, 2, 'Шеф-повар', 'shef-povar'),
(128, 2, 'Экономист (-менеджер)', 'yekonomist-menedzher'),
(129, 2, 'Электрик', 'yelektrik'),
(130, 2, 'Юрист', 'yurist'),
(131, 3, 'По любой специальности', 'po-lyuboj-specialnosti'),
(132, 3, 'Администратор', 'administrator'),
(133, 3, 'Арт-директор', 'art-direktor'),
(134, 3, 'Бармен', 'barmen'),
(135, 3, 'Бренд-менеджер', 'brend-menedzher'),
(136, 3, 'Бухгалтер', 'buxgalter'),
(137, 3, 'Водитель', 'voditel'),
(138, 3, 'Главный бухгалтер', 'glavnyj-buxgalter'),
(139, 3, 'Дворник', 'dvornik'),
(140, 3, 'Директор', 'direktor'),
(141, 3, 'Директор по закупкам', 'direktor-po-zakupkam'),
(142, 3, 'Директор по маркетингу и рекламе', 'direktor-po-marketingu-i-reklame'),
(143, 3, 'Директор по персоналу', 'direktor-po-personalu'),
(144, 3, 'Диспетчер', 'dispetcher'),
(145, 3, 'Заведующий', 'zaveduyushhij'),
(146, 3, 'Зам.директора', 'zam.direktora'),
(147, 3, 'Инженер', 'inzhener'),
(148, 3, 'Инспектор по кадрам', 'inspektor-po-kadram'),
(149, 3, 'Кассир', 'kassir'),
(150, 3, 'Кладовщик', 'kladovshhik'),
(151, 3, 'Коммерческий директор', 'kommercheskij-direktor'),
(152, 3, 'Кондитер', 'konditer'),
(153, 3, 'Консультант', 'konsultant'),
(154, 3, 'Курьер', 'kurer'),
(155, 3, 'Мастер по маникюру / педикюру', 'master-po-manikyuru-pedikyuru'),
(156, 3, 'Менеджер (-консультант)', 'menedzher-konsultant'),
(157, 3, 'Менеджер по PR', 'menedzher-po-pr'),
(158, 3, 'Менеджер по бронированию', 'menedzher-po-bronirovaniyu'),
(159, 3, 'Менеджер по закупкам', 'menedzher-po-zakupkam'),
(160, 3, 'Менеджер по информационным технологиям', 'menedzher-po-informacionnym-texnologiyam'),
(161, 3, 'Менеджер по маркетингу и рекламе', 'menedzher-po-marketingu-i-reklame'),
(162, 3, 'Менеджер по персоналу', 'menedzher-po-personalu'),
(163, 3, 'Менеджер по продажам', 'menedzher-po-prodazham'),
(164, 3, 'Менеджер по работе с клиентами', 'menedzher-po-rabote-s-klientami'),
(165, 3, 'Менеджер проекта', 'menedzher-proekta'),
(166, 3, 'Начальник отдела', 'nachalnik-otdela'),
(167, 3, 'Оператор ПК', 'operator-pk'),
(168, 3, 'Офис-менеджер', 'ofis-menedzher'),
(169, 3, 'Официант', 'oficiant'),
(170, 3, 'Охранник', 'oxrannik'),
(171, 3, 'Парикмахер', 'parikmaxer'),
(172, 3, 'Переводчик', 'perevodchik'),
(173, 3, 'Повар', 'povar'),
(174, 3, 'Посудомойщик', 'posudomojshhik'),
(175, 3, 'Пресс-секретарь', 'press-sekretar'),
(176, 3, 'Разнорабочий', 'raznorabochij'),
(177, 3, 'Региональный представитель', 'regionalnyj-predstavitel'),
(178, 3, 'Референт', 'referent'),
(179, 3, 'Сантехник', 'santexnik'),
(180, 3, 'Секретарь', 'sekretar'),
(181, 3, 'Секретарь-референт', 'sekretar-referent'),
(182, 3, 'Специалист по закупкам', 'specialist-po-zakupkam'),
(183, 3, 'Специалист по охране труда', 'specialist-po-oxrane-truda'),
(184, 3, 'Специалист по рекламе', 'specialist-po-reklame'),
(185, 3, 'Столяр', 'stolyar'),
(186, 3, 'Супервайзер', 'supervajzer'),
(187, 3, 'Технолог', 'texnolog'),
(188, 3, 'Уборщица', 'uborshhica'),
(189, 3, 'Управляющий', 'upravlyayushhij'),
(190, 3, 'Финансовый директор', 'finansovyj-direktor'),
(191, 3, 'Шеф-повар', 'shef-povar'),
(192, 3, 'Экономист (-менеджер)', 'yekonomist-menedzher'),
(193, 3, 'Электрик', 'yelektrik'),
(194, 3, 'Юрист', 'yurist'),
(195, 4, 'По любой специальности', 'po-lyuboj-specialnosti'),
(196, 4, 'Агроном', 'agronom'),
(197, 4, 'Администратор', 'administrator'),
(198, 4, 'Аудитор', 'auditor'),
(199, 4, 'Банковский служащий', 'bankovskij-sluzhashhij'),
(200, 4, 'Библиотекарь', 'bibliotekar'),
(201, 4, 'Биолог', 'biolog'),
(202, 4, 'Бухгалтер', 'buxgalter'),
(203, 4, 'Водитель', 'voditel'),
(204, 4, 'Воспитатель', 'vospitatel'),
(205, 4, 'Врач', 'vrach'),
(206, 4, 'Главный бухгалтер', 'glavnyj-buxgalter'),
(207, 4, 'Главный инженер', 'glavnyj-inzhener'),
(208, 4, 'Дворник', 'dvornik'),
(209, 4, 'Директор по персоналу', 'direktor-po-personalu'),
(210, 4, 'Диспетчер', 'dispetcher'),
(211, 4, 'Заведующий', 'zaveduyushhij'),
(212, 4, 'Зам.директора', 'zam.direktora'),
(213, 4, 'Инженер', 'inzhener'),
(214, 4, 'Инспектор по кадрам', 'inspektor-po-kadram'),
(215, 4, 'Кассир', 'kassir'),
(216, 4, 'Кладовщик', 'kladovshhik'),
(217, 4, 'Коммерческий директор', 'kommercheskij-direktor'),
(218, 4, 'Консультант', 'konsultant'),
(219, 4, 'Курьер', 'kurer'),
(220, 4, 'Лаборант', 'laborant'),
(221, 4, 'Менеджер по PR', 'menedzher-po-pr'),
(222, 4, 'Менеджер по ВЭД', 'menedzher-po-vyed'),
(223, 4, 'Менеджер по закупкам', 'menedzher-po-zakupkam'),
(224, 4, 'Менеджер по информационным технологиям', 'menedzher-po-informacionnym-texnologiyam'),
(225, 4, 'Менеджер по логистике', 'menedzher-po-logistike'),
(226, 4, 'Менеджер по маркетингу и рекламе', 'menedzher-po-marketingu-i-reklame'),
(227, 4, 'Менеджер по персоналу', 'menedzher-po-personalu'),
(228, 4, 'Методист', 'metodist'),
(229, 4, 'Начальник отдела', 'nachalnik-otdela'),
(230, 4, 'Оператор ПК', 'operator-pk'),
(231, 4, 'Охранник', 'oxrannik'),
(232, 4, 'Оценщик', 'ocenshhik'),
(233, 4, 'Переводчик', 'perevodchik'),
(234, 4, 'Повар', 'povar'),
(235, 4, 'Пресс-секретарь', 'press-sekretar'),
(236, 4, 'Рабочий-строитель', 'rabochij-stroitel'),
(237, 4, 'Разнорабочий', 'raznorabochij'),
(238, 4, 'Ревизор', 'revizor'),
(239, 4, 'Секретарь', 'sekretar'),
(240, 4, 'Секретарь-референт', 'sekretar-referent'),
(241, 4, 'Слесарь (-ремонтник)', 'slesar-remontnik'),
(242, 4, 'Специалист по охране труда', 'specialist-po-oxrane-truda'),
(243, 4, 'Специалист по рекламе', 'specialist-po-reklame'),
(244, 4, 'Сторож', 'storozh'),
(245, 4, 'Таможенный декларант / агент', 'tamozhennyj-deklarant-agent'),
(246, 4, 'Технолог', 'texnolog'),
(247, 4, 'Товаровед', 'tovaroved'),
(248, 4, 'Экономист (-менеджер)', 'yekonomist-menedzher'),
(249, 4, 'Электрик', 'yelektrik'),
(250, 4, 'Юрист', 'yurist'),
(251, 5, 'По любой специальности', 'po-lyuboj-specialnosti'),
(252, 5, 'Администратор баз данных', 'administrator-baz-dannyx'),
(253, 5, 'Аналитик', 'analitik'),
(254, 5, 'Баннермейкер', 'bannermejker'),
(255, 5, 'Бренд-менеджер', 'brend-menedzher'),
(256, 5, 'Бухгалтер', 'buxgalter'),
(257, 5, 'Веб-дизайнер', 'veb-dizajner'),
(258, 5, 'Веб-мастер', 'veb-master'),
(259, 5, 'Верстальщик', 'verstalshhik'),
(260, 5, 'Главный бухгалтер', 'glavnyj-buxgalter'),
(261, 5, 'Главный инженер', 'glavnyj-inzhener'),
(262, 5, 'Директор', 'direktor'),
(263, 5, 'Директор по закупкам', 'direktor-po-zakupkam'),
(264, 5, 'Директор по информационным технологиям', 'direktor-po-informacionnym-texnologiyam'),
(265, 5, 'Директор по маркетингу и рекламе', 'direktor-po-marketingu-i-reklame'),
(266, 5, 'Директор по персоналу', 'direktor-po-personalu'),
(267, 5, 'Зам.директора', 'zam.direktora'),
(268, 5, 'Инженер', 'inzhener'),
(269, 5, 'Инспектор по кадрам', 'inspektor-po-kadram'),
(270, 5, 'Коммерческий директор', 'kommercheskij-direktor'),
(271, 5, 'Консультант', 'konsultant'),
(272, 5, 'Менеджер (-консультант)', 'menedzher-konsultant'),
(273, 5, 'Менеджер интернет-проектов', 'menedzher-internet-proektov'),
(274, 5, 'Менеджер по PR', 'menedzher-po-pr'),
(275, 5, 'Менеджер по информационным технологиям', 'menedzher-po-informacionnym-texnologiyam'),
(276, 5, 'Менеджер по маркетингу и рекламе', 'menedzher-po-marketingu-i-reklame'),
(277, 5, 'Менеджер по персоналу', 'menedzher-po-personalu'),
(278, 5, 'Менеджер по продажам', 'menedzher-po-prodazham'),
(279, 5, 'Менеджер по работе с клиентами', 'menedzher-po-rabote-s-klientami'),
(280, 5, 'Менеджер проекта', 'menedzher-proekta'),
(281, 5, 'Начальник отдела', 'nachalnik-otdela'),
(282, 5, 'Оператор ПК', 'operator-pk'),
(283, 5, 'Офис-менеджер', 'ofis-menedzher'),
(284, 5, 'Переводчик', 'perevodchik'),
(285, 5, 'Пресс-секретарь', 'press-sekretar'),
(286, 5, 'Программист', 'programmist'),
(287, 5, 'Референт', 'referent'),
(288, 5, 'Секретарь', 'sekretar'),
(289, 5, 'Секретарь-референт', 'sekretar-referent'),
(290, 5, 'Системный администратор', 'sistemnyj-administrator'),
(291, 5, 'Специалист по наладке АТС', 'specialist-po-naladke-ats'),
(292, 5, 'Специалист по рекламе', 'specialist-po-reklame'),
(293, 5, 'Специалист по ремонту ПК и оргтехники', 'specialist-po-remontu-pk-i-orgtexniki'),
(294, 5, 'Специалист по тестированию', 'specialist-po-testirovaniyu'),
(295, 5, 'Специалист проводной связи', 'specialist-provodnoj-svyazi'),
(296, 5, 'Супервайзер', 'supervajzer'),
(297, 5, 'Технический аналитик', 'texnicheskij-analitik'),
(298, 5, 'Управляющий', 'upravlyayushhij'),
(299, 5, 'Финансовый директор', 'finansovyj-direktor'),
(300, 5, 'Экономист (-менеджер)', 'yekonomist-menedzher'),
(301, 5, 'Электрик', 'yelektrik'),
(302, 5, 'Юрист', 'yurist'),
(303, 5, 'HTML-кодер', 'html-koder'),
(304, 5, 'Product-менеджер', 'product-menedzher'),
(305, 6, 'По любой специальности', 'po-lyuboj-specialnosti'),
(306, 6, 'Администратор', 'administrator'),
(307, 6, 'Арт-директор', 'art-direktor'),
(308, 6, 'Артист оркестра', 'artist-orkestra'),
(309, 6, 'Бармен', 'barmen'),
(310, 6, 'Бренд-менеджер', 'brend-menedzher'),
(311, 6, 'Бухгалтер', 'buxgalter'),
(312, 6, 'Ведущий программ', 'vedushhij-programm'),
(313, 6, 'Гид', 'gid'),
(314, 6, 'Главный бухгалтер', 'glavnyj-buxgalter'),
(315, 6, 'Главный редактор', 'glavnyj-redaktor'),
(316, 6, 'Декоратор', 'dekorator'),
(317, 6, 'Демонстратор', 'demonstrator'),
(318, 6, 'Дизайнер', 'dizajner'),
(319, 6, 'Диктор', 'diktor'),
(320, 6, 'Директор', 'direktor'),
(321, 6, 'Директор по информационным технологиям', 'direktor-po-informacionnym-texnologiyam'),
(322, 6, 'Директор по маркетингу и рекламе', 'direktor-po-marketingu-i-reklame'),
(323, 6, 'Директор по персоналу', 'direktor-po-personalu'),
(324, 6, 'Журналист', 'zhurnalist'),
(325, 6, 'Заведующий', 'zaveduyushhij'),
(326, 6, 'Зам.директора', 'zam.direktora'),
(327, 6, 'Звукорежиссер', 'zvukorezhisser'),
(328, 6, 'Инженер', 'inzhener'),
(329, 6, 'Инспектор по кадрам', 'inspektor-po-kadram'),
(330, 6, 'Кассир', 'kassir'),
(331, 6, 'Коммерческий директор', 'kommercheskij-direktor'),
(332, 6, 'Консультант', 'konsultant'),
(333, 6, 'Костюмер', 'kostyumer'),
(334, 6, 'Курьер', 'kurer'),
(335, 6, 'Мастер по маникюру / педикюру', 'master-po-manikyuru-pedikyuru'),
(336, 6, 'Менеджер (-консультант)', 'menedzher-konsultant'),
(337, 6, 'Менеджер по PR', 'menedzher-po-pr'),
(338, 6, 'Менеджер по закупкам', 'menedzher-po-zakupkam'),
(339, 6, 'Менеджер по информационным технологиям', 'menedzher-po-informacionnym-texnologiyam'),
(340, 6, 'Менеджер по маркетингу и рекламе', 'menedzher-po-marketingu-i-reklame'),
(341, 6, 'Менеджер по персоналу', 'menedzher-po-personalu'),
(342, 6, 'Менеджер по продажам', 'menedzher-po-prodazham'),
(343, 6, 'Менеджер по работе с клиентами', 'menedzher-po-rabote-s-klientami'),
(344, 6, 'Менеджер проекта', 'menedzher-proekta'),
(345, 6, 'Модель', 'model'),
(346, 6, 'Модельер / Художник-модельер', 'modeler-xudozhnik-modeler'),
(347, 6, 'Начальник отдела', 'nachalnik-otdela'),
(348, 6, 'Оператор', 'operator'),
(349, 6, 'Оператор ПК', 'operator-pk'),
(350, 6, 'Осветитель', 'osvetitel'),
(351, 6, 'Офис-менеджер', 'ofis-menedzher'),
(352, 6, 'Официант', 'oficiant'),
(353, 6, 'Охранник', 'oxrannik'),
(354, 6, 'Парикмахер', 'parikmaxer'),
(355, 6, 'Переводчик', 'perevodchik'),
(356, 6, 'Повар', 'povar'),
(357, 6, 'Портной', 'portnoj'),
(358, 6, 'Посудомойщик', 'posudomojshhik'),
(359, 6, 'Пресс-секретарь', 'press-sekretar'),
(360, 6, 'Продюсер', 'prodyuser'),
(361, 6, 'Разнорабочий', 'raznorabochij'),
(362, 6, 'Расклейщик объявлений', 'rasklejshhik-obyavlenij'),
(363, 6, 'Редактор', 'redaktor'),
(364, 6, 'Режиссер', 'rezhisser'),
(365, 6, 'Референт', 'referent'),
(366, 6, 'Секретарь', 'sekretar'),
(367, 6, 'Секретарь-референт', 'sekretar-referent'),
(368, 6, 'Специалист по рекламе', 'specialist-po-reklame'),
(369, 6, 'Супервайзер', 'supervajzer'),
(370, 6, 'Танцор / Танцовщица', 'tancor-tancovshhica'),
(371, 6, 'Управляющий', 'upravlyayushhij'),
(372, 6, 'Финансовый директор', 'finansovyj-direktor'),
(373, 6, 'Фотограф', 'fotograf'),
(374, 6, 'Художник (-дизайнер)', 'xudozhnik-dizajner'),
(375, 6, 'Швея', 'shveya'),
(376, 6, 'Шеф-повар', 'shef-povar'),
(377, 6, 'Экономист (-менеджер)', 'yekonomist-menedzher'),
(378, 6, 'Электрик', 'yelektrik'),
(379, 6, 'Юрист', 'yurist'),
(380, 7, 'По любой специальности', 'po-lyuboj-specialnosti'),
(381, 7, 'Биолог', 'biolog'),
(382, 7, 'Бренд-менеджер', 'brend-menedzher'),
(383, 7, 'Ветеринар', 'veterinar'),
(384, 7, 'Врач', 'vrach'),
(385, 7, 'Дилер', 'diler'),
(386, 7, 'Директор', 'direktor'),
(387, 7, 'Директор по закупкам', 'direktor-po-zakupkam'),
(388, 7, 'Директор по маркетингу и рекламе', 'direktor-po-marketingu-i-reklame'),
(389, 7, 'Директор по персоналу', 'direktor-po-personalu'),
(390, 7, 'Заведующий', 'zaveduyushhij'),
(391, 7, 'Зам.директора', 'zam.direktora'),
(392, 7, 'Инспектор по кадрам', 'inspektor-po-kadram'),
(393, 7, 'Кассир', 'kassir'),
(394, 7, 'Кладовщик', 'kladovshhik'),
(395, 7, 'Коммерческий директор', 'kommercheskij-direktor'),
(396, 7, 'Консультант', 'konsultant'),
(397, 7, 'Курьер', 'kurer'),
(398, 7, 'Лаборант', 'laborant'),
(399, 7, 'Массажист', 'massazhist'),
(400, 7, 'Медсестра', 'medsestra'),
(401, 7, 'Менеджер (-консультант)', 'menedzher-konsultant'),
(402, 7, 'Менеджер по PR', 'menedzher-po-pr'),
(403, 7, 'Менеджер по ВЭД', 'menedzher-po-vyed'),
(404, 7, 'Менеджер по закупкам', 'menedzher-po-zakupkam'),
(405, 7, 'Менеджер по логистике', 'menedzher-po-logistike'),
(406, 7, 'Менеджер по маркетингу и рекламе', 'menedzher-po-marketingu-i-reklame'),
(407, 7, 'Менеджер по персоналу', 'menedzher-po-personalu'),
(408, 7, 'Менеджер по продажам', 'menedzher-po-prodazham'),
(409, 7, 'Менеджер по работе с клиентами', 'menedzher-po-rabote-s-klientami'),
(410, 7, 'Менеджер проекта', 'menedzher-proekta'),
(411, 7, 'Мерчандайзер', 'merchandajzer'),
(412, 7, 'Начальник отдела', 'nachalnik-otdela'),
(413, 7, 'Начальник цеха', 'nachalnik-cexa'),
(414, 7, 'Оператор ПК', 'operator-pk'),
(415, 7, 'Офис-менеджер', 'ofis-menedzher'),
(416, 7, 'Пресс-секретарь', 'press-sekretar'),
(417, 7, 'Провизор', 'provizor'),
(418, 7, 'Продавец (-консультант)', 'prodavec-konsultant'),
(419, 7, 'Психолог', 'psixolog'),
(420, 7, 'Работник склада', 'rabotnik-sklada'),
(421, 7, 'Распространитель / Промоутер', 'rasprostranitel-promouter'),
(422, 7, 'Региональный представитель', 'regionalnyj-predstavitel'),
(423, 7, 'Референт', 'referent'),
(424, 7, 'Секретарь', 'sekretar'),
(425, 7, 'Секретарь-референт', 'sekretar-referent'),
(426, 7, 'Сиделка', 'sidelka'),
(427, 7, 'Специалист по закупкам', 'specialist-po-zakupkam'),
(428, 7, 'Специалист по клиническим испытаниям', 'specialist-po-klinicheskim-ispytaniyam'),
(429, 7, 'Специалист по охране труда', 'specialist-po-oxrane-truda'),
(430, 7, 'Специалист по рекламе', 'specialist-po-reklame'),
(431, 7, 'Специалист по сертификации', 'specialist-po-sertifikacii'),
(432, 7, 'Сторож', 'storozh'),
(433, 7, 'Супервайзер', 'supervajzer'),
(434, 7, 'Технолог', 'texnolog'),
(435, 7, 'Товаровед', 'tovaroved'),
(436, 7, 'Торговый агент / Агент', 'torgovyj-agent-agent'),
(437, 7, 'Торговый представитель', 'torgovyj-predstavitel'),
(438, 7, 'Управляющий', 'upravlyayushhij'),
(439, 7, 'Фармацевт', 'farmacevt'),
(440, 7, 'Финансовый директор', 'finansovyj-direktor'),
(441, 7, 'Химик', 'ximik'),
(442, 7, 'Экономист (-менеджер)', 'yekonomist-menedzher'),
(443, 7, 'Электрик', 'yelektrik'),
(444, 7, 'Юрист', 'yurist'),
(445, 7, 'Product-менеджер', 'product-menedzher'),
(446, 8, 'По любой специальности', 'po-lyuboj-specialnosti'),
(447, 8, 'Аналитик', 'analitik'),
(448, 8, 'Библиотекарь', 'bibliotekar'),
(449, 8, 'Биолог', 'biolog'),
(450, 8, 'Воспитатель', 'vospitatel'),
(451, 8, 'Главный редактор', 'glavnyj-redaktor'),
(452, 8, 'Директор', 'direktor'),
(453, 8, 'Директор по информационным технологиям', 'direktor-po-informacionnym-texnologiyam'),
(454, 8, 'Директор по маркетингу и рекламе', 'direktor-po-marketingu-i-reklame'),
(455, 8, 'Директор по персоналу', 'direktor-po-personalu'),
(456, 8, 'Заведующий', 'zaveduyushhij'),
(457, 8, 'Зам.директора', 'zam.direktora'),
(458, 8, 'Инспектор по кадрам', 'inspektor-po-kadram'),
(459, 8, 'Коммерческий директор', 'kommercheskij-direktor'),
(460, 8, 'Консультант', 'konsultant'),
(461, 8, 'Куратор', 'kurator'),
(462, 8, 'Лаборант', 'laborant'),
(463, 8, 'Мастер', 'master'),
(464, 8, 'Менеджер (-консультант)', 'menedzher-konsultant'),
(465, 8, 'Менеджер по PR', 'menedzher-po-pr'),
(466, 8, 'Менеджер по маркетингу и рекламе', 'menedzher-po-marketingu-i-reklame'),
(467, 8, 'Менеджер по работе с клиентами', 'menedzher-po-rabote-s-klientami'),
(468, 8, 'Менеджер проекта', 'menedzher-proekta'),
(469, 8, 'Методист', 'metodist'),
(470, 8, 'Оператор ПК', 'operator-pk'),
(471, 8, 'Организатор учебного процесса', 'organizator-uchebnogo-processa'),
(472, 8, 'Офис-менеджер', 'ofis-menedzher'),
(473, 8, 'Переводчик', 'perevodchik'),
(474, 8, 'Преподаватель', 'prepodavatel'),
(475, 8, 'Пресс-секретарь', 'press-sekretar'),
(476, 8, 'Программист', 'programmist'),
(477, 8, 'Психолог', 'psixolog'),
(478, 8, 'Репетитор', 'repetitor'),
(479, 8, 'Референт', 'referent'),
(480, 8, 'Секретарь', 'sekretar'),
(481, 8, 'Секретарь-референт', 'sekretar-referent'),
(482, 8, 'Специалист по рекламе', 'specialist-po-reklame'),
(483, 8, 'Супервайзер', 'supervajzer'),
(484, 8, 'Финансовый директор', 'finansovyj-direktor'),
(485, 8, 'Химик', 'ximik'),
(486, 8, 'Художник (-дизайнер)', 'xudozhnik-dizajner'),
(487, 8, 'Эколог', 'yekolog'),
(488, 8, 'Экономист (-менеджер)', 'yekonomist-menedzher'),
(489, 8, 'Юрист', 'yurist'),
(490, 9, 'По любой специальности', 'po-lyuboj-specialnosti'),
(491, 9, 'Администратор', 'administrator'),
(492, 9, 'Бренд-менеджер', 'brend-menedzher'),
(493, 9, 'Бухгалтер', 'buxgalter'),
(494, 9, 'Веб-мастер', 'veb-master'),
(495, 9, 'Верстальщик', 'verstalshhik'),
(496, 9, 'Главный бухгалтер', 'glavnyj-buxgalter'),
(497, 9, 'Главный редактор', 'glavnyj-redaktor'),
(498, 9, 'Дизайнер', 'dizajner'),
(499, 9, 'Директор', 'direktor'),
(500, 9, 'Директор по закупкам', 'direktor-po-zakupkam'),
(501, 9, 'Директор по информационным технологиям', 'direktor-po-informacionnym-texnologiyam'),
(502, 9, 'Директор по маркетингу и рекламе', 'direktor-po-marketingu-i-reklame'),
(503, 9, 'Директор по персоналу', 'direktor-po-personalu'),
(504, 9, 'Диспетчер', 'dispetcher'),
(505, 9, 'Зам.директора', 'zam.direktora'),
(506, 9, 'Инженер', 'inzhener'),
(507, 9, 'Инспектор по кадрам', 'inspektor-po-kadram'),
(508, 9, 'Кладовщик', 'kladovshhik'),
(509, 9, 'Коммерческий директор', 'kommercheskij-direktor'),
(510, 9, 'Конструктор-технолог', 'konstruktor-texnolog'),
(511, 9, 'Консультант', 'konsultant'),
(512, 9, 'Корректор', 'korrektor'),
(513, 9, 'Корреспондент', 'korrespondent'),
(514, 9, 'Курьер', 'kurer'),
(515, 9, 'Мастер', 'master'),
(516, 9, 'Менеджер (-консультант)', 'menedzher-konsultant'),
(517, 9, 'Менеджер по PR', 'menedzher-po-pr'),
(518, 9, 'Менеджер по закупкам', 'menedzher-po-zakupkam'),
(519, 9, 'Менеджер по информационным технологиям', 'menedzher-po-informacionnym-texnologiyam'),
(520, 9, 'Менеджер по логистике', 'menedzher-po-logistike'),
(521, 9, 'Менеджер по маркетингу и рекламе', 'menedzher-po-marketingu-i-reklame'),
(522, 9, 'Менеджер по персоналу', 'menedzher-po-personalu'),
(523, 9, 'Менеджер по продажам', 'menedzher-po-prodazham'),
(524, 9, 'Менеджер по работе с клиентами', 'menedzher-po-rabote-s-klientami'),
(525, 9, 'Менеджер проекта', 'menedzher-proekta'),
(526, 9, 'Начальник отдела', 'nachalnik-otdela'),
(527, 9, 'Начальник цеха', 'nachalnik-cexa'),
(528, 9, 'Оператор ПК', 'operator-pk'),
(529, 9, 'Офис-менеджер', 'ofis-menedzher'),
(530, 9, 'Переводчик', 'perevodchik'),
(531, 9, 'Печатник', 'pechatnik'),
(532, 9, 'Пресс-секретарь', 'press-sekretar'),
(533, 9, 'Программист', 'programmist'),
(534, 9, 'Работник склада', 'rabotnik-sklada'),
(535, 9, 'Разнорабочий', 'raznorabochij'),
(536, 9, 'Расклейщик объявлений', 'rasklejshhik-obyavlenij'),
(537, 9, 'Распространитель / Промоутер', 'rasprostranitel-promouter'),
(538, 9, 'Региональный представитель', 'regionalnyj-predstavitel'),
(539, 9, 'Редактор', 'redaktor'),
(540, 9, 'Референт', 'referent'),
(541, 9, 'Секретарь', 'sekretar'),
(542, 9, 'Секретарь-референт', 'sekretar-referent'),
(543, 9, 'Специалист по допечатной подготовке', 'specialist-po-dopechatnoj-podgotovke'),
(544, 9, 'Специалист по закупкам', 'specialist-po-zakupkam'),
(545, 9, 'Специалист по охране труда', 'specialist-po-oxrane-truda'),
(546, 9, 'Специалист по рекламе', 'specialist-po-reklame'),
(547, 9, 'Супервайзер', 'supervajzer'),
(548, 9, 'Технолог', 'texnolog'),
(549, 9, 'Торговый агент / Агент', 'torgovyj-agent-agent'),
(550, 9, 'Финансовый директор', 'finansovyj-direktor'),
(551, 9, 'Художник (-дизайнер)', 'xudozhnik-dizajner'),
(552, 9, 'Экономист (-менеджер)', 'yekonomist-menedzher'),
(553, 9, 'Электрик', 'yelektrik'),
(554, 9, 'Юрист', 'yurist'),
(555, 10, 'По любой специальности', 'po-lyuboj-specialnosti'),
(556, 10, 'Бренд-менеджер', 'brend-menedzher'),
(557, 10, 'Бухгалтер', 'buxgalter'),
(558, 10, 'Водитель', 'voditel'),
(559, 10, 'Главный бухгалтер', 'glavnyj-buxgalter'),
(560, 10, 'Главный инженер', 'glavnyj-inzhener'),
(561, 10, 'Дизайнер', 'dizajner'),
(562, 10, 'Дилер', 'diler'),
(563, 10, 'Директор', 'direktor'),
(564, 10, 'Директор по закупкам', 'direktor-po-zakupkam'),
(565, 10, 'Директор по информационным технологиям', 'direktor-po-informacionnym-texnologiyam'),
(566, 10, 'Директор по логистике', 'direktor-po-logistike'),
(567, 10, 'Директор по маркетингу и рекламе', 'direktor-po-marketingu-i-reklame'),
(568, 10, 'Директор по персоналу', 'direktor-po-personalu'),
(569, 10, 'Диспетчер', 'dispetcher'),
(570, 10, 'Заведующий', 'zaveduyushhij'),
(571, 10, 'Закройщик', 'zakrojshhik'),
(572, 10, 'Зам.директора', 'zam.direktora'),
(573, 10, 'Инженер', 'inzhener'),
(574, 10, 'Инженер-конструктор', 'inzhener-konstruktor'),
(575, 10, 'Инспектор по кадрам', 'inspektor-po-kadram'),
(576, 10, 'Кладовщик', 'kladovshhik'),
(577, 10, 'Коммерческий директор', 'kommercheskij-direktor'),
(578, 10, 'Конструктор', 'konstruktor'),
(579, 10, 'Конструктор-технолог', 'konstruktor-texnolog'),
(580, 10, 'Консультант', 'konsultant'),
(581, 10, 'Курьер', 'kurer'),
(582, 10, 'Мастер', 'master'),
(583, 10, 'Менеджер (-консультант)', 'menedzher-konsultant'),
(584, 10, 'Менеджер по PR', 'menedzher-po-pr'),
(585, 10, 'Менеджер по ВЭД', 'menedzher-po-vyed'),
(586, 10, 'Менеджер по закупкам', 'menedzher-po-zakupkam'),
(587, 10, 'Менеджер по информационным технологиям', 'menedzher-po-informacionnym-texnologiyam'),
(588, 10, 'Менеджер по логистике', 'menedzher-po-logistike'),
(589, 10, 'Менеджер по маркетингу и рекламе', 'menedzher-po-marketingu-i-reklame'),
(590, 10, 'Менеджер по персоналу', 'menedzher-po-personalu'),
(591, 10, 'Менеджер по продажам', 'menedzher-po-prodazham'),
(592, 10, 'Менеджер по работе с клиентами', 'menedzher-po-rabote-s-klientami'),
(593, 10, 'Менеджер проекта', 'menedzher-proekta'),
(594, 10, 'Механик', 'mexanik'),
(595, 10, 'Модельер / Художник-модельер', 'modeler-xudozhnik-modeler'),
(596, 10, 'Начальник отдела', 'nachalnik-otdela'),
(597, 10, 'Начальник цеха', 'nachalnik-cexa'),
(598, 10, 'Оператор ПК', 'operator-pk'),
(599, 10, 'Офис-менеджер', 'ofis-menedzher'),
(600, 10, 'Переводчик', 'perevodchik'),
(601, 10, 'Портной', 'portnoj'),
(602, 10, 'Пресс-секретарь', 'press-sekretar'),
(603, 10, 'Программист', 'programmist'),
(604, 10, 'Продавец (-консультант)', 'prodavec-konsultant'),
(605, 10, 'Прораб', 'prorab'),
(606, 10, 'Работник склада', 'rabotnik-sklada'),
(607, 10, 'Разнорабочий', 'raznorabochij'),
(608, 10, 'Распространитель / Промоутер', 'rasprostranitel-promouter'),
(609, 10, 'Региональный представитель', 'regionalnyj-predstavitel'),
(610, 10, 'Референт', 'referent'),
(611, 10, 'Секретарь', 'sekretar'),
(612, 10, 'Секретарь-референт', 'sekretar-referent'),
(613, 10, 'Слесарь (-ремонтник)', 'slesar-remontnik'),
(614, 10, 'Сметчик', 'smetchik'),
(615, 10, 'Специалист по бизнес-процессам', 'specialist-po-biznes-processam'),
(616, 10, 'Специалист по закупкам', 'specialist-po-zakupkam'),
(617, 10, 'Специалист по охране труда', 'specialist-po-oxrane-truda'),
(618, 10, 'Специалист по рекламе', 'specialist-po-reklame'),
(619, 10, 'Специалист по сертификации', 'specialist-po-sertifikacii'),
(620, 10, 'Специалист по тестированию', 'specialist-po-testirovaniyu'),
(621, 10, 'Сторож', 'storozh'),
(622, 10, 'Супервайзер', 'supervajzer'),
(623, 10, 'Технолог', 'texnolog'),
(624, 10, 'Торговый агент / Агент', 'torgovyj-agent-agent'),
(625, 10, 'Торговый представитель', 'torgovyj-predstavitel'),
(626, 10, 'Управляющий', 'upravlyayushhij'),
(627, 10, 'Финансовый директор', 'finansovyj-direktor'),
(628, 10, 'Фрезеровщик', 'frezerovshhik'),
(629, 10, 'Химик', 'ximik'),
(630, 10, 'Швея', 'shveya'),
(631, 10, 'Эколог', 'yekolog'),
(632, 10, 'Экономист (-менеджер)', 'yekonomist-menedzher'),
(633, 10, 'Экспедитор / Логист', 'yekspeditor-logist'),
(634, 10, 'Электрик', 'yelektrik'),
(635, 10, 'Энергетик', 'yenergetik'),
(636, 10, 'ювелир', 'yuvelir'),
(637, 10, 'Юрист', 'yurist'),
(638, 10, 'Product-менеджер', 'product-menedzher'),
(639, 11, 'По любой специальности', 'po-lyuboj-specialnosti'),
(640, 11, 'Бренд-менеджер', 'brend-menedzher'),
(641, 11, 'Бухгалтер', 'buxgalter'),
(642, 11, 'Водитель', 'voditel'),
(643, 11, 'Главный бухгалтер', 'glavnyj-buxgalter'),
(644, 11, 'Главный инженер', 'glavnyj-inzhener'),
(645, 11, 'Дилер', 'diler'),
(646, 11, 'Директор', 'direktor'),
(647, 11, 'Директор по закупкам', 'direktor-po-zakupkam'),
(648, 11, 'Директор по информационным технологиям', 'direktor-po-informacionnym-texnologiyam'),
(649, 11, 'Директор по логистике', 'direktor-po-logistike'),
(650, 11, 'Директор по маркетингу и рекламе', 'direktor-po-marketingu-i-reklame'),
(651, 11, 'Директор по персоналу', 'direktor-po-personalu'),
(652, 11, 'Диспетчер', 'dispetcher'),
(653, 11, 'Заведующий', 'zaveduyushhij'),
(654, 11, 'Зам.директора', 'zam.direktora'),
(655, 11, 'Инженер', 'inzhener'),
(656, 11, 'Инженер-конструктор', 'inzhener-konstruktor'),
(657, 11, 'Инспектор по кадрам', 'inspektor-po-kadram'),
(658, 11, 'Кладовщик', 'kladovshhik'),
(659, 11, 'Коммерческий директор', 'kommercheskij-direktor'),
(660, 11, 'Кондитер', 'konditer'),
(661, 11, 'Конструктор-технолог', 'konstruktor-texnolog'),
(662, 11, 'Консультант', 'konsultant'),
(663, 11, 'Курьер', 'kurer'),
(664, 11, 'Мастер', 'master'),
(665, 11, 'Менеджер (-консультант)', 'menedzher-konsultant'),
(666, 11, 'Менеджер по PR', 'menedzher-po-pr'),
(667, 11, 'Менеджер по ВЭД', 'menedzher-po-vyed'),
(668, 11, 'Менеджер по закупкам', 'menedzher-po-zakupkam'),
(669, 11, 'Менеджер по информационным технологиям', 'menedzher-po-informacionnym-texnologiyam'),
(670, 11, 'Менеджер по логистике', 'menedzher-po-logistike'),
(671, 11, 'Менеджер по маркетингу и рекламе', 'menedzher-po-marketingu-i-reklame'),
(672, 11, 'Менеджер по персоналу', 'menedzher-po-personalu'),
(673, 11, 'Менеджер по продажам', 'menedzher-po-prodazham'),
(674, 11, 'Менеджер по работе с клиентами', 'menedzher-po-rabote-s-klientami'),
(675, 11, 'Менеджер проекта', 'menedzher-proekta'),
(676, 11, 'Механик', 'mexanik'),
(677, 11, 'Начальник отдела', 'nachalnik-otdela'),
(678, 11, 'Начальник цеха', 'nachalnik-cexa'),
(679, 11, 'Оператор ПК', 'operator-pk'),
(680, 11, 'Офис-менеджер', 'ofis-menedzher'),
(681, 11, 'Переводчик', 'perevodchik'),
(682, 11, 'Повар', 'povar'),
(683, 11, 'Посудомойщик', 'posudomojshhik'),
(684, 11, 'Пресс-секретарь', 'press-sekretar'),
(685, 11, 'Программист', 'programmist'),
(686, 11, 'Продавец (-консультант)', 'prodavec-konsultant'),
(687, 11, 'Прораб', 'prorab'),
(688, 11, 'Работник склада', 'rabotnik-sklada'),
(689, 11, 'Разнорабочий', 'raznorabochij'),
(690, 11, 'Распространитель / Промоутер', 'rasprostranitel-promouter'),
(691, 11, 'Региональный представитель', 'regionalnyj-predstavitel'),
(692, 11, 'Референт', 'referent'),
(693, 11, 'Секретарь', 'sekretar'),
(694, 11, 'Секретарь-референт', 'sekretar-referent'),
(695, 11, 'Слесарь (-ремонтник)', 'slesar-remontnik'),
(696, 11, 'Сметчик', 'smetchik'),
(697, 11, 'Специалист по бизнес-процессам', 'specialist-po-biznes-processam'),
(698, 11, 'Специалист по закупкам', 'specialist-po-zakupkam'),
(699, 11, 'Специалист по охране труда', 'specialist-po-oxrane-truda'),
(700, 11, 'Специалист по рекламе', 'specialist-po-reklame'),
(701, 11, 'Специалист по сертификации', 'specialist-po-sertifikacii'),
(702, 11, 'Сторож', 'storozh'),
(703, 11, 'Супервайзер', 'supervajzer'),
(704, 11, 'Технолог', 'texnolog'),
(705, 11, 'Торговый агент / Агент', 'torgovyj-agent-agent'),
(706, 11, 'Торговый представитель', 'torgovyj-predstavitel'),
(707, 11, 'Управляющий', 'upravlyayushhij'),
(708, 11, 'Финансовый директор', 'finansovyj-direktor'),
(709, 11, 'Химик', 'ximik'),
(710, 11, 'Шеф-повар', 'shef-povar'),
(711, 11, 'Эколог', 'yekolog'),
(712, 11, 'Экономист (-менеджер)', 'yekonomist-menedzher'),
(713, 11, 'Экспедитор / Логист', 'yekspeditor-logist'),
(714, 11, 'Электрик', 'yelektrik'),
(715, 11, 'Энергетик', 'yenergetik'),
(716, 11, 'Юрист', 'yurist'),
(717, 11, 'Product-менеджер', 'product-menedzher'),
(718, 12, 'По любой специальности', 'po-lyuboj-specialnosti'),
(719, 12, 'Бренд-менеджер', 'brend-menedzher'),
(720, 12, 'Бухгалтер', 'buxgalter'),
(721, 12, 'Водитель', 'voditel'),
(722, 12, 'Главный бухгалтер', 'glavnyj-buxgalter'),
(723, 12, 'Главный инженер', 'glavnyj-inzhener'),
(724, 12, 'Дизайнер', 'dizajner'),
(725, 12, 'Дилер', 'diler'),
(726, 12, 'Директор', 'direktor'),
(727, 12, 'Директор по закупкам', 'direktor-po-zakupkam'),
(728, 12, 'Директор по информационным технологиям', 'direktor-po-informacionnym-texnologiyam'),
(729, 12, 'Директор по логистике', 'direktor-po-logistike'),
(730, 12, 'Директор по маркетингу и рекламе', 'direktor-po-marketingu-i-reklame'),
(731, 12, 'Директор по персоналу', 'direktor-po-personalu'),
(732, 12, 'Диспетчер', 'dispetcher'),
(733, 12, 'Заведующий', 'zaveduyushhij'),
(734, 12, 'Закройщик', 'zakrojshhik'),
(735, 12, 'Зам.директора', 'zam.direktora'),
(736, 12, 'Инженер', 'inzhener'),
(737, 12, 'Инженер-конструктор', 'inzhener-konstruktor'),
(738, 12, 'Инспектор по кадрам', 'inspektor-po-kadram'),
(739, 12, 'Кладовщик', 'kladovshhik'),
(740, 12, 'Коммерческий директор', 'kommercheskij-direktor'),
(741, 12, 'Конструктор', 'konstruktor'),
(742, 12, 'Конструктор-технолог', 'konstruktor-texnolog'),
(743, 12, 'Консультант', 'konsultant'),
(744, 12, 'Курьер', 'kurer'),
(745, 12, 'Мастер', 'master'),
(746, 12, 'Менеджер (-консультант)', 'menedzher-konsultant'),
(747, 12, 'Менеджер по PR', 'menedzher-po-pr'),
(748, 12, 'Менеджер по ВЭД', 'menedzher-po-vyed'),
(749, 12, 'Менеджер по закупкам', 'menedzher-po-zakupkam'),
(750, 12, 'Менеджер по информационным технологиям', 'menedzher-po-informacionnym-texnologiyam'),
(751, 12, 'Менеджер по логистике', 'menedzher-po-logistike'),
(752, 12, 'Менеджер по маркетингу и рекламе', 'menedzher-po-marketingu-i-reklame'),
(753, 12, 'Менеджер по персоналу', 'menedzher-po-personalu'),
(754, 12, 'Менеджер по продажам', 'menedzher-po-prodazham'),
(755, 12, 'Менеджер по работе с клиентами', 'menedzher-po-rabote-s-klientami'),
(756, 12, 'Менеджер проекта', 'menedzher-proekta'),
(757, 12, 'Механик', 'mexanik'),
(758, 12, 'Начальник отдела', 'nachalnik-otdela'),
(759, 12, 'Начальник цеха', 'nachalnik-cexa'),
(760, 12, 'Оператор ПК', 'operator-pk'),
(761, 12, 'Офис-менеджер', 'ofis-menedzher'),
(762, 12, 'Переводчик', 'perevodchik'),
(763, 12, 'Портной', 'portnoj'),
(764, 12, 'Пресс-секретарь', 'press-sekretar'),
(765, 12, 'Программист', 'programmist'),
(766, 12, 'Продавец (-консультант)', 'prodavec-konsultant'),
(767, 12, 'Прораб', 'prorab'),
(768, 12, 'Работник склада', 'rabotnik-sklada'),
(769, 12, 'Разнорабочий', 'raznorabochij'),
(770, 12, 'Региональный представитель', 'regionalnyj-predstavitel'),
(771, 12, 'Референт', 'referent'),
(772, 12, 'Секретарь', 'sekretar'),
(773, 12, 'Секретарь-референт', 'sekretar-referent'),
(774, 12, 'Слесарь (-ремонтник)', 'slesar-remontnik'),
(775, 12, 'Сметчик', 'smetchik'),
(776, 12, 'Специалист по бизнес-процессам', 'specialist-po-biznes-processam'),
(777, 12, 'Специалист по закупкам', 'specialist-po-zakupkam'),
(778, 12, 'Специалист по охране труда', 'specialist-po-oxrane-truda'),
(779, 12, 'Специалист по рекламе', 'specialist-po-reklame'),
(780, 12, 'Специалист по сертификации', 'specialist-po-sertifikacii'),
(781, 12, 'Специалист по тестированию', 'specialist-po-testirovaniyu'),
(782, 12, 'Сторож', 'storozh'),
(783, 12, 'Супервайзер', 'supervajzer'),
(784, 12, 'Технолог', 'texnolog'),
(785, 12, 'Торговый агент / Агент', 'torgovyj-agent-agent'),
(786, 12, 'Торговый представитель', 'torgovyj-predstavitel'),
(787, 12, 'Управляющий', 'upravlyayushhij'),
(788, 12, 'Финансовый директор', 'finansovyj-direktor'),
(789, 12, 'Фрезеровщик', 'frezerovshhik'),
(790, 12, 'Химик', 'ximik'),
(791, 12, 'Эколог', 'yekolog'),
(792, 12, 'Экономист (-менеджер)', 'yekonomist-menedzher'),
(793, 12, 'Экспедитор / Логист', 'yekspeditor-logist'),
(794, 12, 'Электрик', 'yelektrik'),
(795, 12, 'Энергетик', 'yenergetik'),
(796, 12, 'Юрист', 'yurist'),
(797, 12, 'Product-менеджер', 'product-menedzher'),
(798, 13, 'По любой специальности', 'po-lyuboj-specialnosti'),
(799, 13, 'Администратор', 'administrator'),
(800, 13, 'Аналитик', 'analitik'),
(801, 13, 'Арт-директор', 'art-direktor'),
(802, 13, 'Бренд-менеджер', 'brend-menedzher'),
(803, 13, 'Бухгалтер', 'buxgalter'),
(804, 13, 'Веб-мастер', 'veb-master'),
(805, 13, 'Ведущий программ', 'vedushhij-programm'),
(806, 13, 'Верстальщик', 'verstalshhik'),
(807, 13, 'Главный бухгалтер', 'glavnyj-buxgalter'),
(808, 13, 'Главный редактор', 'glavnyj-redaktor'),
(809, 13, 'Демонстратор', 'demonstrator'),
(810, 13, 'Дизайнер', 'dizajner'),
(811, 13, 'Диктор', 'diktor'),
(812, 13, 'Директор', 'direktor'),
(813, 13, 'Директор по информационным технологиям', 'direktor-po-informacionnym-texnologiyam'),
(814, 13, 'Директор по маркетингу и рекламе', 'direktor-po-marketingu-i-reklame'),
(815, 13, 'Директор по персоналу', 'direktor-po-personalu'),
(816, 13, 'Журналист', 'zhurnalist'),
(817, 13, 'Зам.директора', 'zam.direktora'),
(818, 13, 'Звукорежиссер', 'zvukorezhisser'),
(819, 13, 'Инспектор по кадрам', 'inspektor-po-kadram'),
(820, 13, 'Интервьюер', 'intervyuer'),
(821, 13, 'Коммерческий директор', 'kommercheskij-direktor'),
(822, 13, 'Консультант', 'konsultant'),
(823, 13, 'Копирайтер', 'kopirajter'),
(824, 13, 'Корректор', 'korrektor'),
(825, 13, 'Корреспондент', 'korrespondent'),
(826, 13, 'Курьер', 'kurer'),
(827, 13, 'Макетчик', 'maketchik'),
(828, 13, 'Медиапланнер', 'mediaplanner'),
(829, 13, 'Менеджер (-консультант)', 'menedzher-konsultant'),
(830, 13, 'Менеджер по PR', 'menedzher-po-pr'),
(831, 13, 'Менеджер по ВЭД', 'menedzher-po-vyed'),
(832, 13, 'Менеджер по закупкам', 'menedzher-po-zakupkam'),
(833, 13, 'Менеджер по информационным технологиям', 'menedzher-po-informacionnym-texnologiyam'),
(834, 13, 'Менеджер по логистике', 'menedzher-po-logistike'),
(835, 13, 'Менеджер по маркетингу и рекламе', 'menedzher-po-marketingu-i-reklame'),
(836, 13, 'Менеджер по персоналу', 'menedzher-po-personalu'),
(837, 13, 'Менеджер по продажам', 'menedzher-po-prodazham'),
(838, 13, 'Менеджер по работе с клиентами', 'menedzher-po-rabote-s-klientami'),
(839, 13, 'Менеджер проекта', 'menedzher-proekta'),
(840, 13, 'Мерчандайзер', 'merchandajzer'),
(841, 13, 'Начальник отдела', 'nachalnik-otdela'),
(842, 13, 'Оператор', 'operator'),
(843, 13, 'Оператор ПК', 'operator-pk'),
(844, 13, 'Офис-менеджер', 'ofis-menedzher'),
(845, 13, 'Переводчик', 'perevodchik'),
(846, 13, 'Пресс-секретарь', 'press-sekretar'),
(847, 13, 'Программист', 'programmist'),
(848, 13, 'Психолог', 'psixolog'),
(849, 13, 'Расклейщик объявлений', 'rasklejshhik-obyavlenij'),
(850, 13, 'Распространитель / Промоутер', 'rasprostranitel-promouter'),
(851, 13, 'Региональный представитель', 'regionalnyj-predstavitel'),
(852, 13, 'Редактор', 'redaktor'),
(853, 13, 'Режиссер', 'rezhisser'),
(854, 13, 'Референт', 'referent'),
(855, 13, 'Секретарь', 'sekretar'),
(856, 13, 'Секретарь-референт', 'sekretar-referent'),
(857, 13, 'Специалист по бизнес-процессам', 'specialist-po-biznes-processam'),
(858, 13, 'Специалист по допечатной подготовке', 'specialist-po-dopechatnoj-podgotovke'),
(859, 13, 'Специалист по рекламе', 'specialist-po-reklame'),
(860, 13, 'Супервайзер', 'supervajzer'),
(861, 13, 'Технический аналитик', 'texnicheskij-analitik'),
(862, 13, 'Торговый агент / Агент', 'torgovyj-agent-agent'),
(863, 13, 'Финансовый директор', 'finansovyj-direktor'),
(864, 13, 'Фотограф', 'fotograf'),
(865, 13, 'Художник (-дизайнер)', 'xudozhnik-dizajner'),
(866, 13, 'Экономист (-менеджер)', 'yekonomist-menedzher'),
(867, 13, 'Юрист', 'yurist'),
(868, 14, 'По любой специальности', 'po-lyuboj-specialnosti'),
(869, 14, 'Аудитор', 'auditor'),
(870, 14, 'Бренд-менеджер', 'brend-menedzher'),
(871, 14, 'Бухгалтер', 'buxgalter'),
(872, 14, 'Главный бухгалтер', 'glavnyj-buxgalter'),
(873, 14, 'Директор', 'direktor'),
(874, 14, 'Директор по информационным технологиям', 'direktor-po-informacionnym-texnologiyam'),
(875, 14, 'Директор по маркетингу и рекламе', 'direktor-po-marketingu-i-reklame'),
(876, 14, 'Директор по персоналу', 'direktor-po-personalu'),
(877, 14, 'Зам.директора', 'zam.direktora'),
(878, 14, 'Инспектор по кадрам', 'inspektor-po-kadram'),
(879, 14, 'Кассир', 'kassir'),
(880, 14, 'Коммерческий директор', 'kommercheskij-direktor'),
(881, 14, 'Консультант', 'konsultant'),
(882, 14, 'Курьер', 'kurer'),
(883, 14, 'Менеджер (-консультант)', 'menedzher-konsultant'),
(884, 14, 'Менеджер по PR', 'menedzher-po-pr'),
(885, 14, 'Менеджер по информационным технологиям', 'menedzher-po-informacionnym-texnologiyam'),
(886, 14, 'Менеджер по маркетингу и рекламе', 'menedzher-po-marketingu-i-reklame'),
(887, 14, 'Менеджер по персоналу', 'menedzher-po-personalu'),
(888, 14, 'Менеджер по продажам', 'menedzher-po-prodazham'),
(889, 14, 'Менеджер по работе с клиентами', 'menedzher-po-rabote-s-klientami'),
(890, 14, 'Начальник отдела', 'nachalnik-otdela'),
(891, 14, 'Оператор ПК', 'operator-pk'),
(892, 14, 'Офис-менеджер', 'ofis-menedzher'),
(893, 14, 'Оценщик', 'ocenshhik'),
(894, 14, 'Пресс-секретарь', 'press-sekretar'),
(895, 14, 'Продавец (-консультант)', 'prodavec-konsultant'),
(896, 14, 'Региональный представитель', 'regionalnyj-predstavitel'),
(897, 14, 'Референт', 'referent'),
(898, 14, 'Секретарь', 'sekretar'),
(899, 14, 'Секретарь-референт', 'sekretar-referent'),
(900, 14, 'Специалист по рекламе', 'specialist-po-reklame'),
(901, 14, 'Супервайзер', 'supervajzer'),
(902, 14, 'Торговый агент / Агент', 'torgovyj-agent-agent'),
(903, 14, 'Управляющий', 'upravlyayushhij'),
(904, 14, 'Финансовый директор', 'finansovyj-direktor'),
(905, 14, 'Экономист (-менеджер)', 'yekonomist-menedzher'),
(906, 14, 'Юрист', 'yurist'),
(907, 15, 'По любой специальности', 'po-lyuboj-specialnosti'),
(908, 15, 'Архитектор', 'arxitektor'),
(909, 15, 'Бренд-менеджер', 'brend-menedzher'),
(910, 15, 'Брокер / Трейдер', 'broker-trejder'),
(911, 15, 'Бухгалтер', 'buxgalter'),
(912, 15, 'Водитель', 'voditel'),
(913, 15, 'Главный бухгалтер', 'glavnyj-buxgalter'),
(914, 15, 'Главный инженер', 'glavnyj-inzhener'),
(915, 15, 'Грузчик', 'gruzchik'),
(916, 15, 'Дизайнер', 'dizajner'),
(917, 15, 'Директор', 'direktor'),
(918, 15, 'Директор по закупкам', 'direktor-po-zakupkam'),
(919, 15, 'Директор по информационным технологиям', 'direktor-po-informacionnym-texnologiyam'),
(920, 15, 'Директор по логистике', 'direktor-po-logistike'),
(921, 15, 'Директор по маркетингу и рекламе', 'direktor-po-marketingu-i-reklame'),
(922, 15, 'Директор по персоналу', 'direktor-po-personalu'),
(923, 15, 'Зам.директора', 'zam.direktora'),
(924, 15, 'Инженер', 'inzhener'),
(925, 15, 'Инженер-конструктор', 'inzhener-konstruktor'),
(926, 15, 'Инженер-строитель', 'inzhener-stroitel'),
(927, 15, 'Инспектор по кадрам', 'inspektor-po-kadram'),
(928, 15, 'Каменщик', 'kamenshhik'),
(929, 15, 'Коммерческий директор', 'kommercheskij-direktor'),
(930, 15, 'Конструктор', 'konstruktor'),
(931, 15, 'Конструктор-технолог', 'konstruktor-texnolog'),
(932, 15, 'Консультант', 'konsultant'),
(933, 15, 'Курьер', 'kurer'),
(934, 15, 'Маклер', 'makler'),
(935, 15, 'Маляр', 'malyar'),
(936, 15, 'Мастер', 'master'),
(937, 15, 'Машинист крана', 'mashinist-krana'),
(938, 15, 'Менеджер (-консультант)', 'menedzher-konsultant'),
(939, 15, 'Менеджер по PR', 'menedzher-po-pr'),
(940, 15, 'Менеджер по закупкам', 'menedzher-po-zakupkam'),
(941, 15, 'Менеджер по информационным технологиям', 'menedzher-po-informacionnym-texnologiyam'),
(942, 15, 'Менеджер по логистике', 'menedzher-po-logistike'),
(943, 15, 'Менеджер по маркетингу и рекламе', 'menedzher-po-marketingu-i-reklame'),
(944, 15, 'Менеджер по персоналу', 'menedzher-po-personalu'),
(945, 15, 'Менеджер по продажам', 'menedzher-po-prodazham'),
(946, 15, 'Менеджер по работе с клиентами', 'menedzher-po-rabote-s-klientami'),
(947, 15, 'Менеджер проекта', 'menedzher-proekta'),
(948, 15, 'Начальник отдела', 'nachalnik-otdela'),
(949, 15, 'Оператор ПК', 'operator-pk'),
(950, 15, 'Офис-менеджер', 'ofis-menedzher'),
(951, 15, 'Плиточник', 'plitochnik'),
(952, 15, 'Пресс-секретарь', 'press-sekretar'),
(953, 15, 'Прораб', 'prorab'),
(954, 15, 'Работник склада', 'rabotnik-sklada'),
(955, 15, 'Рабочий-строитель', 'rabochij-stroitel'),
(956, 15, 'Разнорабочий', 'raznorabochij'),
(957, 15, 'Региональный представитель', 'regionalnyj-predstavitel'),
(958, 15, 'Референт', 'referent'),
(959, 15, 'Риэлтор', 'riyeltor'),
(960, 15, 'Сантехник', 'santexnik'),
(961, 15, 'Секретарь', 'sekretar'),
(962, 15, 'Секретарь-референт', 'sekretar-referent'),
(963, 15, 'Слесарь (-ремонтник)', 'slesar-remontnik'),
(964, 15, 'Сметчик', 'smetchik'),
(965, 15, 'Специалист по закупкам', 'specialist-po-zakupkam'),
(966, 15, 'Специалист по охране труда', 'specialist-po-oxrane-truda'),
(967, 15, 'Специалист по рекламе', 'specialist-po-reklame'),
(968, 15, 'Столяр', 'stolyar'),
(969, 15, 'Сторож', 'storozh'),
(970, 15, 'Супервайзер', 'supervajzer'),
(971, 15, 'Технолог', 'texnolog'),
(972, 15, 'Торговый агент / Агент', 'torgovyj-agent-agent'),
(973, 15, 'Управляющий', 'upravlyayushhij'),
(974, 15, 'Финансовый директор', 'finansovyj-direktor'),
(975, 15, 'Экономист (-менеджер)', 'yekonomist-menedzher'),
(976, 15, 'Экскаваторщик', 'yekskavatorshhik'),
(977, 15, 'Электрик', 'yelektrik'),
(978, 15, 'Юрист', 'yurist'),
(979, 16, 'По любой специальности', 'po-lyuboj-specialnosti'),
(980, 16, 'Бренд-менеджер', 'brend-menedzher'),
(981, 16, 'Бухгалтер', 'buxgalter'),
(982, 16, 'Водитель', 'voditel'),
(983, 16, 'Главный бухгалтер', 'glavnyj-buxgalter'),
(984, 16, 'Демонстратор', 'demonstrator'),
(985, 16, 'Дилер', 'diler'),
(986, 16, 'Директор', 'direktor'),
(987, 16, 'Директор по закупкам', 'direktor-po-zakupkam'),
(988, 16, 'Директор по информационным технологиям', 'direktor-po-informacionnym-texnologiyam'),
(989, 16, 'Директор по логистике', 'direktor-po-logistike'),
(990, 16, 'Директор по маркетингу и рекламе', 'direktor-po-marketingu-i-reklame'),
(991, 16, 'Директор по персоналу', 'direktor-po-personalu'),
(992, 16, 'Заведующий', 'zaveduyushhij'),
(993, 16, 'Зам.директора', 'zam.direktora'),
(994, 16, 'Инженер', 'inzhener'),
(995, 16, 'Инспектор по кадрам', 'inspektor-po-kadram'),
(996, 16, 'Кассир', 'kassir'),
(997, 16, 'Кладовщик', 'kladovshhik'),
(998, 16, 'Коммерческий директор', 'kommercheskij-direktor'),
(999, 16, 'Консультант', 'konsultant'),
(1000, 16, 'Курьер', 'kurer'),
(1001, 16, 'Менеджер (-консультант)', 'menedzher-konsultant'),
(1002, 16, 'Менеджер по PR', 'menedzher-po-pr'),
(1003, 16, 'Менеджер по ВЭД', 'menedzher-po-vyed'),
(1004, 16, 'Менеджер по закупкам', 'menedzher-po-zakupkam'),
(1005, 16, 'Менеджер по информационным технологиям', 'menedzher-po-informacionnym-texnologiyam'),
(1006, 16, 'Менеджер по логистике', 'menedzher-po-logistike'),
(1007, 16, 'Менеджер по маркетингу и рекламе', 'menedzher-po-marketingu-i-reklame'),
(1008, 16, 'Менеджер по персоналу', 'menedzher-po-personalu'),
(1009, 16, 'Менеджер по продажам', 'menedzher-po-prodazham'),
(1010, 16, 'Менеджер по работе с клиентами', 'menedzher-po-rabote-s-klientami'),
(1011, 16, 'Менеджер проекта', 'menedzher-proekta'),
(1012, 16, 'Мерчандайзер', 'merchandajzer'),
(1013, 16, 'Начальник отдела', 'nachalnik-otdela'),
(1014, 16, 'Оператор ПК', 'operator-pk'),
(1015, 16, 'Офис-менеджер', 'ofis-menedzher'),
(1016, 16, 'Охранник', 'oxrannik'),
(1017, 16, 'Оценщик', 'ocenshhik'),
(1018, 16, 'Переводчик', 'perevodchik'),
(1019, 16, 'Пресс-секретарь', 'press-sekretar'),
(1020, 16, 'Продавец (-консультант)', 'prodavec-konsultant'),
(1021, 16, 'Работник склада', 'rabotnik-sklada'),
(1022, 16, 'Распространитель / Промоутер', 'rasprostranitel-promouter'),
(1023, 16, 'Региональный представитель', 'regionalnyj-predstavitel'),
(1024, 16, 'Референт', 'referent'),
(1025, 16, 'Секретарь', 'sekretar'),
(1026, 16, 'Секретарь-референт', 'sekretar-referent'),
(1027, 16, 'Специалист по бизнес-процессам', 'specialist-po-biznes-processam'),
(1028, 16, 'Специалист по закупкам', 'specialist-po-zakupkam'),
(1029, 16, 'Специалист по охране труда', 'specialist-po-oxrane-truda'),
(1030, 16, 'Специалист по рекламе', 'specialist-po-reklame'),
(1031, 16, 'Специалист по сертификации', 'specialist-po-sertifikacii'),
(1032, 16, 'Сторож', 'storozh'),
(1033, 16, 'Супервайзер', 'supervajzer'),
(1034, 16, 'Технический аналитик', 'texnicheskij-analitik'),
(1035, 16, 'Товаровед', 'tovaroved'),
(1036, 16, 'Торговый агент / Агент', 'torgovyj-agent-agent'),
(1037, 16, 'Торговый представитель', 'torgovyj-predstavitel'),
(1038, 16, 'Управляющий', 'upravlyayushhij'),
(1039, 16, 'Финансовый директор', 'finansovyj-direktor'),
(1040, 16, 'Экономист (-менеджер)', 'yekonomist-menedzher'),
(1041, 16, 'Экспедитор / Логист', 'yekspeditor-logist'),
(1042, 16, 'Электрик', 'yelektrik'),
(1043, 16, 'Юрист', 'yurist'),
(1044, 16, 'Product-менеджер', 'product-menedzher'),
(1045, 17, 'По любой специальности', 'po-lyuboj-specialnosti'),
(1046, 17, 'Бренд-менеджер', 'brend-menedzher'),
(1047, 17, 'Бухгалтер', 'buxgalter'),
(1048, 17, 'Водитель', 'voditel'),
(1049, 17, 'Главный бухгалтер', 'glavnyj-buxgalter'),
(1050, 17, 'Демонстратор', 'demonstrator'),
(1051, 17, 'Дизайнер', 'dizajner'),
(1052, 17, 'Дилер', 'diler'),
(1053, 17, 'Директор', 'direktor'),
(1054, 17, 'Директор по закупкам', 'direktor-po-zakupkam'),
(1055, 17, 'Директор по информационным технологиям', 'direktor-po-informacionnym-texnologiyam'),
(1056, 17, 'Директор по логистике', 'direktor-po-logistike'),
(1057, 17, 'Директор по маркетингу и рекламе', 'direktor-po-marketingu-i-reklame'),
(1058, 17, 'Директор по персоналу', 'direktor-po-personalu'),
(1059, 17, 'Заведующий', 'zaveduyushhij'),
(1060, 17, 'Зам.директора', 'zam.direktora'),
(1061, 17, 'Инженер', 'inzhener'),
(1062, 17, 'Инспектор по кадрам', 'inspektor-po-kadram'),
(1063, 17, 'Кассир', 'kassir'),
(1064, 17, 'Кладовщик', 'kladovshhik'),
(1065, 17, 'Коммерческий директор', 'kommercheskij-direktor'),
(1066, 17, 'Консультант', 'konsultant'),
(1067, 17, 'Курьер', 'kurer'),
(1068, 17, 'Менеджер (-консультант)', 'menedzher-konsultant'),
(1069, 17, 'Менеджер по PR', 'menedzher-po-pr'),
(1070, 17, 'Менеджер по ВЭД', 'menedzher-po-vyed'),
(1071, 17, 'Менеджер по закупкам', 'menedzher-po-zakupkam'),
(1072, 17, 'Менеджер по информационным технологиям', 'menedzher-po-informacionnym-texnologiyam'),
(1073, 17, 'Менеджер по логистике', 'menedzher-po-logistike'),
(1074, 17, 'Менеджер по маркетингу и рекламе', 'menedzher-po-marketingu-i-reklame'),
(1075, 17, 'Менеджер по персоналу', 'menedzher-po-personalu'),
(1076, 17, 'Менеджер по продажам', 'menedzher-po-prodazham'),
(1077, 17, 'Менеджер по работе с клиентами', 'menedzher-po-rabote-s-klientami'),
(1078, 17, 'Менеджер проекта', 'menedzher-proekta'),
(1079, 17, 'Мерчандайзер', 'merchandajzer'),
(1080, 17, 'Начальник отдела', 'nachalnik-otdela'),
(1081, 17, 'Оператор ПК', 'operator-pk'),
(1082, 17, 'Офис-менеджер', 'ofis-menedzher'),
(1083, 17, 'Охранник', 'oxrannik'),
(1084, 17, 'Оценщик', 'ocenshhik'),
(1085, 17, 'Переводчик', 'perevodchik'),
(1086, 17, 'Пресс-секретарь', 'press-sekretar'),
(1087, 17, 'Программист', 'programmist'),
(1088, 17, 'Продавец (-консультант)', 'prodavec-konsultant'),
(1089, 17, 'Работник склада', 'rabotnik-sklada'),
(1090, 17, 'Распространитель / Промоутер', 'rasprostranitel-promouter'),
(1091, 17, 'Региональный представитель', 'regionalnyj-predstavitel'),
(1092, 17, 'Референт', 'referent'),
(1093, 17, 'Секретарь', 'sekretar'),
(1094, 17, 'Секретарь-референт', 'sekretar-referent'),
(1095, 17, 'Специалист по бизнес-процессам', 'specialist-po-biznes-processam'),
(1096, 17, 'Специалист по закупкам', 'specialist-po-zakupkam'),
(1097, 17, 'Специалист по охране труда', 'specialist-po-oxrane-truda'),
(1098, 17, 'Специалист по рекламе', 'specialist-po-reklame'),
(1099, 17, 'Специалист по сертификации', 'specialist-po-sertifikacii'),
(1100, 17, 'Сторож', 'storozh'),
(1101, 17, 'Супервайзер', 'supervajzer'),
(1102, 17, 'Технический аналитик', 'texnicheskij-analitik'),
(1103, 17, 'Товаровед', 'tovaroved'),
(1104, 17, 'Торговый агент / Агент', 'torgovyj-agent-agent'),
(1105, 17, 'Торговый представитель', 'torgovyj-predstavitel'),
(1106, 17, 'Управляющий', 'upravlyayushhij'),
(1107, 17, 'Финансовый директор', 'finansovyj-direktor'),
(1108, 17, 'Экономист (-менеджер)', 'yekonomist-menedzher'),
(1109, 17, 'Экспедитор / Логист', 'yekspeditor-logist'),
(1110, 17, 'Электрик', 'yelektrik'),
(1111, 17, 'Юрист', 'yurist'),
(1112, 17, 'Product-менеджер', 'product-menedzher'),
(1113, 18, 'По любой специальности', 'po-lyuboj-specialnosti'),
(1114, 18, 'Бренд-менеджер', 'brend-menedzher'),
(1115, 18, 'Бухгалтер', 'buxgalter'),
(1116, 18, 'Водитель', 'voditel'),
(1117, 18, 'Главный бухгалтер', 'glavnyj-buxgalter'),
(1118, 18, 'Демонстратор', 'demonstrator'),
(1119, 18, 'Дилер', 'diler'),
(1120, 18, 'Директор', 'direktor'),
(1121, 18, 'Директор по закупкам', 'direktor-po-zakupkam'),
(1122, 18, 'Директор по информационным технологиям', 'direktor-po-informacionnym-texnologiyam'),
(1123, 18, 'Директор по логистике', 'direktor-po-logistike'),
(1124, 18, 'Директор по маркетингу и рекламе', 'direktor-po-marketingu-i-reklame'),
(1125, 18, 'Директор по персоналу', 'direktor-po-personalu'),
(1126, 18, 'Заведующий', 'zaveduyushhij'),
(1127, 18, 'Зам.директора', 'zam.direktora'),
(1128, 18, 'Инженер', 'inzhener'),
(1129, 18, 'Инспектор по кадрам', 'inspektor-po-kadram'),
(1130, 18, 'Кассир', 'kassir'),
(1131, 18, 'Кладовщик', 'kladovshhik'),
(1132, 18, 'Коммерческий директор', 'kommercheskij-direktor'),
(1133, 18, 'Консультант', 'konsultant'),
(1134, 18, 'Курьер', 'kurer'),
(1135, 18, 'Менеджер (-консультант)', 'menedzher-konsultant'),
(1136, 18, 'Менеджер по PR', 'menedzher-po-pr'),
(1137, 18, 'Менеджер по ВЭД', 'menedzher-po-vyed'),
(1138, 18, 'Менеджер по закупкам', 'menedzher-po-zakupkam'),
(1139, 18, 'Менеджер по информационным технологиям', 'menedzher-po-informacionnym-texnologiyam'),
(1140, 18, 'Менеджер по логистике', 'menedzher-po-logistike'),
(1141, 18, 'Менеджер по маркетингу и рекламе', 'menedzher-po-marketingu-i-reklame'),
(1142, 18, 'Менеджер по персоналу', 'menedzher-po-personalu'),
(1143, 18, 'Менеджер по продажам', 'menedzher-po-prodazham'),
(1144, 18, 'Менеджер по работе с клиентами', 'menedzher-po-rabote-s-klientami'),
(1145, 18, 'Менеджер проекта', 'menedzher-proekta'),
(1146, 18, 'Мерчандайзер', 'merchandajzer'),
(1147, 18, 'Начальник отдела', 'nachalnik-otdela'),
(1148, 18, 'Оператор ПК', 'operator-pk'),
(1149, 18, 'Офис-менеджер', 'ofis-menedzher'),
(1150, 18, 'Охранник', 'oxrannik'),
(1151, 18, 'Оценщик', 'ocenshhik'),
(1152, 18, 'Переводчик', 'perevodchik'),
(1153, 18, 'Пресс-секретарь', 'press-sekretar'),
(1154, 18, 'Программист', 'programmist'),
(1155, 18, 'Продавец (-консультант)', 'prodavec-konsultant'),
(1156, 18, 'Работник склада', 'rabotnik-sklada'),
(1157, 18, 'Распространитель / Промоутер', 'rasprostranitel-promouter'),
(1158, 18, 'Региональный представитель', 'regionalnyj-predstavitel'),
(1159, 18, 'Референт', 'referent'),
(1160, 18, 'Секретарь', 'sekretar'),
(1161, 18, 'Секретарь-референт', 'sekretar-referent'),
(1162, 18, 'Специалист по бизнес-процессам', 'specialist-po-biznes-processam'),
(1163, 18, 'Специалист по закупкам', 'specialist-po-zakupkam'),
(1164, 18, 'Специалист по охране труда', 'specialist-po-oxrane-truda'),
(1165, 18, 'Специалист по рекламе', 'specialist-po-reklame'),
(1166, 18, 'Специалист по ремонту ПК и оргтехники', 'specialist-po-remontu-pk-i-orgtexniki'),
(1167, 18, 'Специалист по сертификации', 'specialist-po-sertifikacii'),
(1168, 18, 'Сторож', 'storozh'),
(1169, 18, 'Супервайзер', 'supervajzer'),
(1170, 18, 'Технический аналитик', 'texnicheskij-analitik'),
(1171, 18, 'Товаровед', 'tovaroved'),
(1172, 18, 'Торговый агент / Агент', 'torgovyj-agent-agent'),
(1173, 18, 'Торговый представитель', 'torgovyj-predstavitel'),
(1174, 18, 'Управляющий', 'upravlyayushhij'),
(1175, 18, 'Финансовый директор', 'finansovyj-direktor'),
(1176, 18, 'Экономист (-менеджер)', 'yekonomist-menedzher'),
(1177, 18, 'Экспедитор / Логист', 'yekspeditor-logist'),
(1178, 18, 'Электрик', 'yelektrik'),
(1179, 18, 'Юрист', 'yurist'),
(1180, 18, 'Product-менеджер', 'product-menedzher'),
(1181, 19, 'По любой специальности', 'po-lyuboj-specialnosti'),
(1182, 19, 'Бренд-менеджер', 'brend-menedzher'),
(1183, 19, 'Бухгалтер', 'buxgalter'),
(1184, 19, 'Водитель', 'voditel'),
(1185, 19, 'Главный бухгалтер', 'glavnyj-buxgalter'),
(1186, 19, 'Дилер', 'diler'),
(1187, 19, 'Директор', 'direktor'),
(1188, 19, 'Директор по закупкам', 'direktor-po-zakupkam'),
(1189, 19, 'Директор по информационным технологиям', 'direktor-po-informacionnym-texnologiyam'),
(1190, 19, 'Директор по логистике', 'direktor-po-logistike'),
(1191, 19, 'Директор по маркетингу и рекламе', 'direktor-po-marketingu-i-reklame'),
(1192, 19, 'Директор по персоналу', 'direktor-po-personalu'),
(1193, 19, 'Заведующий', 'zaveduyushhij'),
(1194, 19, 'Зам.директора', 'zam.direktora'),
(1195, 19, 'Инспектор по кадрам', 'inspektor-po-kadram'),
(1196, 19, 'Кассир', 'kassir'),
(1197, 19, 'Кладовщик', 'kladovshhik'),
(1198, 19, 'Коммерческий директор', 'kommercheskij-direktor'),
(1199, 19, 'Кондитер', 'konditer'),
(1200, 19, 'Консультант', 'konsultant'),
(1201, 19, 'Курьер', 'kurer'),
(1202, 19, 'Менеджер (-консультант)', 'menedzher-konsultant'),
(1203, 19, 'Менеджер по PR', 'menedzher-po-pr'),
(1204, 19, 'Менеджер по ВЭД', 'menedzher-po-vyed'),
(1205, 19, 'Менеджер по закупкам', 'menedzher-po-zakupkam'),
(1206, 19, 'Менеджер по информационным технологиям', 'menedzher-po-informacionnym-texnologiyam'),
(1207, 19, 'Менеджер по логистике', 'menedzher-po-logistike'),
(1208, 19, 'Менеджер по маркетингу и рекламе', 'menedzher-po-marketingu-i-reklame'),
(1209, 19, 'Менеджер по персоналу', 'menedzher-po-personalu'),
(1210, 19, 'Менеджер по продажам', 'menedzher-po-prodazham'),
(1211, 19, 'Менеджер по работе с клиентами', 'menedzher-po-rabote-s-klientami'),
(1212, 19, 'Менеджер проекта', 'menedzher-proekta'),
(1213, 19, 'Мерчандайзер', 'merchandajzer'),
(1214, 19, 'Начальник отдела', 'nachalnik-otdela'),
(1215, 19, 'Оператор ПК', 'operator-pk'),
(1216, 19, 'Офис-менеджер', 'ofis-menedzher'),
(1217, 19, 'Охранник', 'oxrannik'),
(1218, 19, 'Оценщик', 'ocenshhik'),
(1219, 19, 'Переводчик', 'perevodchik'),
(1220, 19, 'Посудомойщик', 'posudomojshhik'),
(1221, 19, 'Пресс-секретарь', 'press-sekretar'),
(1222, 19, 'Продавец (-консультант)', 'prodavec-konsultant'),
(1223, 19, 'Работник склада', 'rabotnik-sklada'),
(1224, 19, 'Распространитель / Промоутер', 'rasprostranitel-promouter'),
(1225, 19, 'Региональный представитель', 'regionalnyj-predstavitel'),
(1226, 19, 'Референт', 'referent'),
(1227, 19, 'Секретарь', 'sekretar'),
(1228, 19, 'Секретарь-референт', 'sekretar-referent'),
(1229, 19, 'Специалист по бизнес-процессам', 'specialist-po-biznes-processam'),
(1230, 19, 'Специалист по закупкам', 'specialist-po-zakupkam'),
(1231, 19, 'Специалист по охране труда', 'specialist-po-oxrane-truda'),
(1232, 19, 'Специалист по рекламе', 'specialist-po-reklame'),
(1233, 19, 'Специалист по сертификации', 'specialist-po-sertifikacii'),
(1234, 19, 'Сторож', 'storozh'),
(1235, 19, 'Супервайзер', 'supervajzer'),
(1236, 19, 'Товаровед', 'tovaroved'),
(1237, 19, 'Торговый агент / Агент', 'torgovyj-agent-agent'),
(1238, 19, 'Торговый представитель', 'torgovyj-predstavitel'),
(1239, 19, 'Управляющий', 'upravlyayushhij'),
(1240, 19, 'Финансовый директор', 'finansovyj-direktor'),
(1241, 19, 'Шеф-повар', 'shef-povar'),
(1242, 19, 'Экономист (-менеджер)', 'yekonomist-menedzher'),
(1243, 19, 'Экспедитор / Логист', 'yekspeditor-logist'),
(1244, 19, 'Электрик', 'yelektrik'),
(1245, 19, 'Юрист', 'yurist'),
(1246, 19, 'Product-менеджер', 'product-menedzher'),
(1247, 20, 'По любой специальности', 'po-lyuboj-specialnosti'),
(1248, 20, 'Бренд-менеджер', 'brend-menedzher'),
(1249, 20, 'Бухгалтер', 'buxgalter'),
(1250, 20, 'Водитель', 'voditel'),
(1251, 20, 'Водитель-международник', 'voditel-mezhdunarodnik'),
(1252, 20, 'Главный бухгалтер', 'glavnyj-buxgalter'),
(1253, 20, 'Дилер', 'diler'),
(1254, 20, 'Директор', 'direktor'),
(1255, 20, 'Директор по закупкам', 'direktor-po-zakupkam'),
(1256, 20, 'Директор по информационным технологиям', 'direktor-po-informacionnym-texnologiyam'),
(1257, 20, 'Директор по логистике', 'direktor-po-logistike'),
(1258, 20, 'Директор по маркетингу и рекламе', 'direktor-po-marketingu-i-reklame'),
(1259, 20, 'Директор по персоналу', 'direktor-po-personalu'),
(1260, 20, 'Заведующий', 'zaveduyushhij'),
(1261, 20, 'Зам.директора', 'zam.direktora'),
(1262, 20, 'Инженер', 'inzhener'),
(1263, 20, 'Инспектор по кадрам', 'inspektor-po-kadram'),
(1264, 20, 'Кассир', 'kassir'),
(1265, 20, 'Кладовщик', 'kladovshhik'),
(1266, 20, 'Коммерческий директор', 'kommercheskij-direktor'),
(1267, 20, 'Консультант', 'konsultant'),
(1268, 20, 'Курьер', 'kurer'),
(1269, 20, 'Менеджер (-консультант)', 'menedzher-konsultant'),
(1270, 20, 'Менеджер по PR', 'menedzher-po-pr'),
(1271, 20, 'Менеджер по ВЭД', 'menedzher-po-vyed'),
(1272, 20, 'Менеджер по закупкам', 'menedzher-po-zakupkam'),
(1273, 20, 'Менеджер по информационным технологиям', 'menedzher-po-informacionnym-texnologiyam'),
(1274, 20, 'Менеджер по логистике', 'menedzher-po-logistike'),
(1275, 20, 'Менеджер по маркетингу и рекламе', 'menedzher-po-marketingu-i-reklame'),
(1276, 20, 'Менеджер по персоналу', 'menedzher-po-personalu'),
(1277, 20, 'Менеджер по продажам', 'menedzher-po-prodazham'),
(1278, 20, 'Менеджер по работе с клиентами', 'menedzher-po-rabote-s-klientami'),
(1279, 20, 'Менеджер проекта', 'menedzher-proekta'),
(1280, 20, 'Начальник отдела', 'nachalnik-otdela'),
(1281, 20, 'Оператор ПК', 'operator-pk'),
(1282, 20, 'Офис-менеджер', 'ofis-menedzher'),
(1283, 20, 'Охранник', 'oxrannik'),
(1284, 20, 'Оценщик', 'ocenshhik'),
(1285, 20, 'Переводчик', 'perevodchik'),
(1286, 20, 'Пресс-секретарь', 'press-sekretar'),
(1287, 20, 'Продавец (-консультант)', 'prodavec-konsultant'),
(1288, 20, 'Работник склада', 'rabotnik-sklada'),
(1289, 20, 'Региональный представитель', 'regionalnyj-predstavitel'),
(1290, 20, 'Референт', 'referent'),
(1291, 20, 'Секретарь', 'sekretar'),
(1292, 20, 'Секретарь-референт', 'sekretar-referent'),
(1293, 20, 'Специалист по бизнес-процессам', 'specialist-po-biznes-processam'),
(1294, 20, 'Специалист по закупкам', 'specialist-po-zakupkam'),
(1295, 20, 'Специалист по охране труда', 'specialist-po-oxrane-truda'),
(1296, 20, 'Специалист по рекламе', 'specialist-po-reklame'),
(1297, 20, 'Специалист по сертификации', 'specialist-po-sertifikacii'),
(1298, 20, 'Сторож', 'storozh'),
(1299, 20, 'Супервайзер', 'supervajzer'),
(1300, 20, 'Товаровед', 'tovaroved'),
(1301, 20, 'Торговый агент / Агент', 'torgovyj-agent-agent'),
(1302, 20, 'Торговый представитель', 'torgovyj-predstavitel'),
(1303, 20, 'Управляющий', 'upravlyayushhij'),
(1304, 20, 'Финансовый директор', 'finansovyj-direktor'),
(1305, 20, 'Экономист (-менеджер)', 'yekonomist-menedzher'),
(1306, 20, 'Экспедитор / Логист', 'yekspeditor-logist'),
(1307, 20, 'Электрик', 'yelektrik'),
(1308, 20, 'Юрист', 'yurist'),
(1309, 20, 'Product-менеджер', 'product-menedzher'),
(1310, 21, 'По любой специальности', 'po-lyuboj-specialnosti'),
(1311, 21, 'Бренд-менеджер', 'brend-menedzher'),
(1312, 21, 'Бухгалтер', 'buxgalter'),
(1313, 21, 'Водитель', 'voditel'),
(1314, 21, 'Главный бухгалтер', 'glavnyj-buxgalter'),
(1315, 21, 'Демонстратор', 'demonstrator'),
(1316, 21, 'Дилер', 'diler'),
(1317, 21, 'Директор', 'direktor'),
(1318, 21, 'Директор по закупкам', 'direktor-po-zakupkam'),
(1319, 21, 'Директор по информационным технологиям', 'direktor-po-informacionnym-texnologiyam'),
(1320, 21, 'Директор по логистике', 'direktor-po-logistike'),
(1321, 21, 'Директор по маркетингу и рекламе', 'direktor-po-marketingu-i-reklame'),
(1322, 21, 'Директор по персоналу', 'direktor-po-personalu'),
(1323, 21, 'Заведующий', 'zaveduyushhij'),
(1324, 21, 'Зам.директора', 'zam.direktora'),
(1325, 21, 'Инженер', 'inzhener'),
(1326, 21, 'Инспектор по кадрам', 'inspektor-po-kadram'),
(1327, 21, 'Кассир', 'kassir'),
(1328, 21, 'Кладовщик', 'kladovshhik'),
(1329, 21, 'Коммерческий директор', 'kommercheskij-direktor'),
(1330, 21, 'Консультант', 'konsultant'),
(1331, 21, 'Курьер', 'kurer'),
(1332, 21, 'Менеджер (-консультант)', 'menedzher-konsultant'),
(1333, 21, 'Менеджер по PR', 'menedzher-po-pr'),
(1334, 21, 'Менеджер по ВЭД', 'menedzher-po-vyed'),
(1335, 21, 'Менеджер по закупкам', 'menedzher-po-zakupkam'),
(1336, 21, 'Менеджер по информационным технологиям', 'menedzher-po-informacionnym-texnologiyam'),
(1337, 21, 'Менеджер по логистике', 'menedzher-po-logistike'),
(1338, 21, 'Менеджер по маркетингу и рекламе', 'menedzher-po-marketingu-i-reklame'),
(1339, 21, 'Менеджер по персоналу', 'menedzher-po-personalu'),
(1340, 21, 'Менеджер по продажам', 'menedzher-po-prodazham'),
(1341, 21, 'Менеджер по работе с клиентами', 'menedzher-po-rabote-s-klientami'),
(1342, 21, 'Менеджер проекта', 'menedzher-proekta'),
(1343, 21, 'Мерчандайзер', 'merchandajzer'),
(1344, 21, 'Начальник отдела', 'nachalnik-otdela'),
(1345, 21, 'Оператор ПК', 'operator-pk'),
(1346, 21, 'Офис-менеджер', 'ofis-menedzher'),
(1347, 21, 'Охранник', 'oxrannik'),
(1348, 21, 'Оценщик', 'ocenshhik'),
(1349, 21, 'Переводчик', 'perevodchik'),
(1350, 21, 'Портной', 'portnoj'),
(1351, 21, 'Пресс-секретарь', 'press-sekretar'),
(1352, 21, 'Продавец (-консультант)', 'prodavec-konsultant'),
(1353, 21, 'Работник склада', 'rabotnik-sklada'),
(1354, 21, 'Распространитель / Промоутер', 'rasprostranitel-promouter'),
(1355, 21, 'Региональный представитель', 'regionalnyj-predstavitel'),
(1356, 21, 'Референт', 'referent'),
(1357, 21, 'Секретарь', 'sekretar'),
(1358, 21, 'Секретарь-референт', 'sekretar-referent'),
(1359, 21, 'Специалист по бизнес-процессам', 'specialist-po-biznes-processam'),
(1360, 21, 'Специалист по закупкам', 'specialist-po-zakupkam'),
(1361, 21, 'Специалист по охране труда', 'specialist-po-oxrane-truda'),
(1362, 21, 'Специалист по рекламе', 'specialist-po-reklame'),
(1363, 21, 'Специалист по сертификации', 'specialist-po-sertifikacii'),
(1364, 21, 'Сторож', 'storozh'),
(1365, 21, 'Супервайзер', 'supervajzer'),
(1366, 21, 'Товаровед', 'tovaroved'),
(1367, 21, 'Торговый агент / Агент', 'torgovyj-agent-agent'),
(1368, 21, 'Торговый представитель', 'torgovyj-predstavitel'),
(1369, 21, 'Управляющий', 'upravlyayushhij'),
(1370, 21, 'Финансовый директор', 'finansovyj-direktor'),
(1371, 21, 'Экономист (-менеджер)', 'yekonomist-menedzher'),
(1372, 21, 'Экспедитор / Логист', 'yekspeditor-logist'),
(1373, 21, 'Электрик', 'yelektrik'),
(1374, 21, 'ювелир', 'yuvelir'),
(1375, 21, 'Юрист', 'yurist'),
(1376, 21, 'Product-менеджер', 'product-menedzher'),
(1377, 22, 'По любой специальности', 'po-lyuboj-specialnosti'),
(1378, 22, 'Автомаляр', 'avtomalyar'),
(1379, 22, 'Автослесарь', 'avtoslesar'),
(1380, 22, 'Бренд-менеджер', 'brend-menedzher'),
(1381, 22, 'Бухгалтер', 'buxgalter'),
(1382, 22, 'Водитель', 'voditel'),
(1383, 22, 'Водитель-международник', 'voditel-mezhdunarodnik'),
(1384, 22, 'Главный бухгалтер', 'glavnyj-buxgalter'),
(1385, 22, 'Грузчик', 'gruzchik'),
(1386, 22, 'Дилер', 'diler'),
(1387, 22, 'Директор', 'direktor'),
(1388, 22, 'Директор по закупкам', 'direktor-po-zakupkam'),
(1389, 22, 'Директор по информационным технологиям', 'direktor-po-informacionnym-texnologiyam'),
(1390, 22, 'Директор по логистике', 'direktor-po-logistike'),
(1391, 22, 'Директор по маркетингу и рекламе', 'direktor-po-marketingu-i-reklame'),
(1392, 22, 'Директор по персоналу', 'direktor-po-personalu'),
(1393, 22, 'Диспетчер', 'dispetcher'),
(1394, 22, 'Зам.директора', 'zam.direktora'),
(1395, 22, 'Инженер', 'inzhener'),
(1396, 22, 'Инженер-конструктор', 'inzhener-konstruktor'),
(1397, 22, 'Инспектор по кадрам', 'inspektor-po-kadram'),
(1398, 22, 'Кассир', 'kassir'),
(1399, 22, 'Кладовщик', 'kladovshhik'),
(1400, 22, 'Коммерческий директор', 'kommercheskij-direktor'),
(1401, 22, 'Конструктор', 'konstruktor'),
(1402, 22, 'Конструктор-технолог', 'konstruktor-texnolog'),
(1403, 22, 'Консультант', 'konsultant'),
(1404, 22, 'Курьер', 'kurer'),
(1405, 22, 'Мастер', 'master'),
(1406, 22, 'Машинист крана', 'mashinist-krana'),
(1407, 22, 'Менеджер (-консультант)', 'menedzher-konsultant'),
(1408, 22, 'Менеджер по PR', 'menedzher-po-pr'),
(1409, 22, 'Менеджер по ВЭД', 'menedzher-po-vyed'),
(1410, 22, 'Менеджер по закупкам', 'menedzher-po-zakupkam'),
(1411, 22, 'Менеджер по информационным технологиям', 'menedzher-po-informacionnym-texnologiyam'),
(1412, 22, 'Менеджер по логистике', 'menedzher-po-logistike'),
(1413, 22, 'Менеджер по маркетингу и рекламе', 'menedzher-po-marketingu-i-reklame'),
(1414, 22, 'Менеджер по персоналу', 'menedzher-po-personalu'),
(1415, 22, 'Менеджер по продажам', 'menedzher-po-prodazham'),
(1416, 22, 'Менеджер по работе с клиентами', 'menedzher-po-rabote-s-klientami'),
(1417, 22, 'Менеджер проекта', 'menedzher-proekta'),
(1418, 22, 'Механик', 'mexanik'),
(1419, 22, 'Начальник отдела', 'nachalnik-otdela'),
(1420, 22, 'Начальник цеха', 'nachalnik-cexa'),
(1421, 22, 'Оператор ПК', 'operator-pk'),
(1422, 22, 'Офис-менеджер', 'ofis-menedzher'),
(1423, 22, 'Охранник', 'oxrannik'),
(1424, 22, 'Переводчик', 'perevodchik'),
(1425, 22, 'Пресс-секретарь', 'press-sekretar'),
(1426, 22, 'Продавец (-консультант)', 'prodavec-konsultant'),
(1427, 22, 'Работник склада', 'rabotnik-sklada'),
(1428, 22, 'Разнорабочий', 'raznorabochij'),
(1429, 22, 'Региональный представитель', 'regionalnyj-predstavitel'),
(1430, 22, 'Референт', 'referent'),
(1431, 22, 'Секретарь', 'sekretar'),
(1432, 22, 'Секретарь-референт', 'sekretar-referent'),
(1433, 22, 'Слесарь (-ремонтник)', 'slesar-remontnik'),
(1434, 22, 'Специалист по бизнес-процессам', 'specialist-po-biznes-processam'),
(1435, 22, 'Специалист по закупкам', 'specialist-po-zakupkam'),
(1436, 22, 'Специалист по охране труда', 'specialist-po-oxrane-truda'),
(1437, 22, 'Специалист по рекламе', 'specialist-po-reklame'),
(1438, 22, 'Сторож', 'storozh'),
(1439, 22, 'Супервайзер', 'supervajzer'),
(1440, 22, 'Таможенный декларант / агент', 'tamozhennyj-deklarant-agent'),
(1441, 22, 'Торговый агент / Агент', 'torgovyj-agent-agent'),
(1442, 22, 'Торговый представитель', 'torgovyj-predstavitel'),
(1443, 22, 'Финансовый директор', 'finansovyj-direktor'),
(1444, 22, 'Фрезеровщик', 'frezerovshhik'),
(1445, 22, 'Экономист (-менеджер)', 'yekonomist-menedzher'),
(1446, 22, 'Экскаваторщик', 'yekskavatorshhik'),
(1447, 22, 'Экспедитор / Логист', 'yekspeditor-logist'),
(1448, 22, 'Электрик', 'yelektrik'),
(1449, 22, 'Юрист', 'yurist'),
(1450, 23, 'По любой специальности', 'po-lyuboj-specialnosti'),
(1451, 23, 'Администратор', 'administrator'),
(1452, 23, 'Бренд-менеджер', 'brend-menedzher'),
(1453, 23, 'Водитель', 'voditel'),
(1454, 23, 'Водитель-международник', 'voditel-mezhdunarodnik'),
(1455, 23, 'Гид', 'gid'),
(1456, 23, 'Директор', 'direktor'),
(1457, 23, 'Директор по информационным технологиям', 'direktor-po-informacionnym-texnologiyam'),
(1458, 23, 'Директор по маркетингу и рекламе', 'direktor-po-marketingu-i-reklame'),
(1459, 23, 'Директор по персоналу', 'direktor-po-personalu'),
(1460, 23, 'Зам.директора', 'zam.direktora'),
(1461, 23, 'Инспектор по кадрам', 'inspektor-po-kadram'),
(1462, 23, 'Коммерческий директор', 'kommercheskij-direktor'),
(1463, 23, 'Консультант', 'konsultant'),
(1464, 23, 'Курьер', 'kurer'),
(1465, 23, 'Массажист', 'massazhist'),
(1466, 23, 'Менеджер (-консультант)', 'menedzher-konsultant'),
(1467, 23, 'Менеджер по PR', 'menedzher-po-pr'),
(1468, 23, 'Менеджер по бронированию', 'menedzher-po-bronirovaniyu'),
(1469, 23, 'Менеджер по информационным технологиям', 'menedzher-po-informacionnym-texnologiyam'),
(1470, 23, 'Менеджер по маркетингу и рекламе', 'menedzher-po-marketingu-i-reklame'),
(1471, 23, 'Менеджер по продажам', 'menedzher-po-prodazham'),
(1472, 23, 'Менеджер по работе с клиентами', 'menedzher-po-rabote-s-klientami'),
(1473, 23, 'Менеджер проекта', 'menedzher-proekta'),
(1474, 23, 'Начальник отдела', 'nachalnik-otdela'),
(1475, 23, 'Оператор ПК', 'operator-pk'),
(1476, 23, 'Офис-менеджер', 'ofis-menedzher'),
(1477, 23, 'Переводчик', 'perevodchik'),
(1478, 23, 'Посудомойщик', 'posudomojshhik'),
(1479, 23, 'Пресс-секретарь', 'press-sekretar'),
(1480, 23, 'Региональный представитель', 'regionalnyj-predstavitel'),
(1481, 23, 'Референт', 'referent'),
(1482, 23, 'Секретарь', 'sekretar'),
(1483, 23, 'Секретарь-референт', 'sekretar-referent'),
(1484, 23, 'Специалист по рекламе', 'specialist-po-reklame'),
(1485, 23, 'Супервайзер', 'supervajzer'),
(1486, 23, 'Товаровед', 'tovaroved'),
(1487, 23, 'Торговый агент / Агент', 'torgovyj-agent-agent'),
(1488, 23, 'Тренер', 'trener'),
(1489, 23, 'Финансовый директор', 'finansovyj-direktor'),
(1490, 23, 'Экономист (-менеджер)', 'yekonomist-menedzher'),
(1491, 23, 'Юрист', 'yurist'),
(1492, 24, 'По любой специальности', 'po-lyuboj-specialnosti'),
(1493, 24, 'Аналитик', 'analitik'),
(1494, 24, 'Аудитор', 'auditor'),
(1495, 24, 'Банковский служащий', 'bankovskij-sluzhashhij'),
(1496, 24, 'Бренд-менеджер', 'brend-menedzher'),
(1497, 24, 'Брокер / Трейдер', 'broker-trejder'),
(1498, 24, 'Бухгалтер', 'buxgalter'),
(1499, 24, 'Главный бухгалтер', 'glavnyj-buxgalter'),
(1500, 24, 'Дилер', 'diler'),
(1501, 24, 'Директор', 'direktor'),
(1502, 24, 'Директор по информационным технологиям', 'direktor-po-informacionnym-texnologiyam'),
(1503, 24, 'Директор по маркетингу и рекламе', 'direktor-po-marketingu-i-reklame'),
(1504, 24, 'Директор по персоналу', 'direktor-po-personalu'),
(1505, 24, 'Заведующий', 'zaveduyushhij'),
(1506, 24, 'Зам.директора', 'zam.direktora'),
(1507, 24, 'Инспектор по кадрам', 'inspektor-po-kadram'),
(1508, 24, 'Кассир', 'kassir'),
(1509, 24, 'Коммерческий директор', 'kommercheskij-direktor'),
(1510, 24, 'Консультант', 'konsultant'),
(1511, 24, 'Куратор', 'kurator'),
(1512, 24, 'Курьер', 'kurer'),
(1513, 24, 'Маклер', 'makler'),
(1514, 24, 'Менеджер (-консультант)', 'menedzher-konsultant'),
(1515, 24, 'Менеджер по PR', 'menedzher-po-pr'),
(1516, 24, 'Менеджер по ВЭД', 'menedzher-po-vyed'),
(1517, 24, 'Менеджер по информационным технологиям', 'menedzher-po-informacionnym-texnologiyam'),
(1518, 24, 'Менеджер по маркетингу и рекламе', 'menedzher-po-marketingu-i-reklame'),
(1519, 24, 'Менеджер по персоналу', 'menedzher-po-personalu'),
(1520, 24, 'Менеджер по продажам', 'menedzher-po-prodazham'),
(1521, 24, 'Менеджер по работе с клиентами', 'menedzher-po-rabote-s-klientami'),
(1522, 24, 'Менеджер проекта', 'menedzher-proekta'),
(1523, 24, 'Начальник отдела', 'nachalnik-otdela'),
(1524, 24, 'Оператор ПК', 'operator-pk'),
(1525, 24, 'Операционист', 'operacionist'),
(1526, 24, 'Офис-менеджер', 'ofis-menedzher'),
(1527, 24, 'Охранник', 'oxrannik'),
(1528, 24, 'Оценщик', 'ocenshhik'),
(1529, 24, 'Переводчик', 'perevodchik'),
(1530, 24, 'Пресс-секретарь', 'press-sekretar'),
(1531, 24, 'Программист', 'programmist'),
(1532, 24, 'Продавец (-консультант)', 'prodavec-konsultant'),
(1533, 24, 'Ревизор', 'revizor'),
(1534, 24, 'Региональный представитель', 'regionalnyj-predstavitel'),
(1535, 24, 'Референт', 'referent'),
(1536, 24, 'Риэлтор', 'riyeltor'),
(1537, 24, 'Секретарь', 'sekretar'),
(1538, 24, 'Секретарь-референт', 'sekretar-referent'),
(1539, 24, 'Специалист по бизнес-процессам', 'specialist-po-biznes-processam'),
(1540, 24, 'Специалист по регистрации', 'specialist-po-registracii'),
(1541, 24, 'Специалист по рекламе', 'specialist-po-reklame'),
(1542, 24, 'Супервайзер', 'supervajzer'),
(1543, 24, 'Таможенный декларант / агент', 'tamozhennyj-deklarant-agent'),
(1544, 24, 'Технический аналитик', 'texnicheskij-analitik'),
(1545, 24, 'Торговый агент / Агент', 'torgovyj-agent-agent'),
(1546, 24, 'Управляющий', 'upravlyayushhij'),
(1547, 24, 'Финансовый директор', 'finansovyj-direktor'),
(1548, 24, 'Экономист (-менеджер)', 'yekonomist-menedzher'),
(1549, 24, 'Юрист', 'yurist'),
(1550, 24, 'Product-менеджер', 'product-menedzher')";

?>